### ISSUE TITLE
Unable to message on freshly restored channel

### ISSUE THREAD

**Issue by chahat-arora** [mattermost/mattermost#12145]
### Summary
When restoring a channel through the CLI command: `https://docs.mattermost.com/administration/command-line-tools.html#mattermost-channel-restore`
Then the users are not able to message in the channel for approx 15-20 minutes.

### Steps to reproduce

1. Archive a channel
2. Unarchive the channel using CLI command given above.
3. Now, try to message on the channel.
Server logs say 'Can not post to deleted channel'

### Expected behavior
User must able to message in the channel after the channel is visible in the channel list.

#### OS
- Ubuntu 18.04.3 LTS
#### Mattermost Server Version
- 5.14.0
#### Browser
- both chrome and firefox
#### Logs
- `{"level":"error","ts":1568120567.1900868,"caller":"mlog/log.go:173","msg":"Can not post to deleted channel.","path":"/api/v4/posts","request_id":"dwc6sa8bw7r7t83n83dunffayy","ip_addr":"::1","user_id":"ixesmpkpptdwxqcou9cx8gnr5o","method":"POST","err_where":"createPost","http_code":400,"err_details":""}`
- Running on Docker

**Comment by amyblais** [comment]
Hi @chahat-arora, Would you be open to reviewing this page and sending us the relevant information about your environment: https://docs.mattermost.com/process/support.html#general-questions-for-any-issues?

**Comment by chahat-arora** [comment]
Done @amyblais

**Comment by lieut-data** [comment]
@chahat-arora, sorry about this pain point. Right now, our CLI is able to modify the state in the database, but it has no way of notifying the individual server instances of this change, and so the server holds on to this state longer than is desirable due to internal caching.

You can restart the server to immediately rectify this problem. We are steadily moving our CLI to a model that works largely by interacting with the server over the API, allowing to properly invalidate caches throughout the cluster. @grundleborg, is there a ticket we can link to track this issue in relation to that effort?

**Comment by grundleborg** [comment]
There is an Epic https://mattermost.atlassian.net/browse/MM-18663 but it is not yet fully populated - we're **tentatively** planning to make `mmctl` the default during Q4-2019 (so in the next 3 months).

**Comment by hanzei** [comment]
Closing as an old, stale issue.
