### ISSUE TITLE
Autoscrolling when a new message has been received does not work and a pop-up is displayed

### ISSUE THREAD

**Issue by carlspring** [mattermost/mattermost#16099]
#### Summary

Each time I get a new message in a window that I'm already chatting, I get a link to scroll down to the "latest messages". I was already at the bottom of the list of messages and there were no new messages. This is happening constantly since we upgraded to 5.28.1.

```
Mattermost Team Edition
All your team communication in one place, instantly searchable and accessible anywhere.

Mattermost Version: 5.28.1
Database Schema Version: 5.28.0
Database: postgres
```

#### Steps to reproduce

User 1 sends message to User 2 (when User 2 is already at the bottom of the message list in the same chat window, where User 1 is messaging them).

#### Expected behavior

The text should auto-scroll. It should only **_not_** auto-scroll, if the recipient has scrolled up (or is still scrolling up).

There should also be some sort of icon that enables/disables this sort of functionality.

#### Observed behavior (that appears unintentional) 

![image](https://user-images.githubusercontent.com/1436265/97335107-5b7b9c80-1875-11eb-9e90-8152acf57665.png)

#### Possible fixes

N/A

**Comment by amyblais** [comment]
@carlspring What environment are you on (OS and version)?
Do you see any errors in server logs or in the developer console?
Which version did you upgrade from?

**Comment by carlspring** [comment]
Hi,

I have:
```
Google Chrome | 86.0.4240.111 (Official Build) (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Linux
JavaScript | V8 8.6.395.17
Flash | 32.0.0.445 /home/carlspring/.config/google-chrome/PepperFlash/32.0.0.445/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
```

No errors in the log that I can see.

**Comment by amyblais** [comment]
I wasn't able to reproduce this so far. Is this happening with all users on your server? Is this happening consistently?

**Comment by amyblais** [comment]
@sudheerDev Would you be able to help take a look at this?

**Comment by sudheerDev** [comment]
@carlspring Can you replicate this on incognito?

**Comment by carlspring** [comment]
I've tried different settings and the problem seems to occur on HiDPI screens with gnome scale at 200%. If I set scale to 100%, it works fine, but I can't read anything.


![Screenshot from 2020-10-29 22-02-44](https://user-images.githubusercontent.com/1436265/97637476-a42c8480-1a32-11eb-8f33-1a1a94c7276b.png)

**Comment by carlspring** [comment]
> @carlspring Can you replicate this in an incognito window?

I forgot to mention, yes, this also happens in incognito mode.

An interesting observation is that if you switch to another window and somebody messages you in the meantime, this issue always happens.

**Comment by lieut-data** [comment]
> An interesting observation is that if you switch to another window and somebody messages you in the meantime, this issue always happens.

I believe this is by design, since if the window isn't focused, it's possible to miss messages.

I suspect the issue is specific to the window scaling and calculations we do to determine if the user is scrolled to the bottom or not. @amyblais, I think we can file a ticket for this one right away, and can let the webapp team triage further.

**Comment by amyblais** [comment]
Ticket here: https://mattermost.atlassian.net/browse/MM-30234.

**Comment by carlspring** [comment]
This used to work fine before, so I don't think the current (I assume new) design is right. It should automatically scroll down, even it you were in another window/tab and then you switch back to this. It would be great to have an option for this and to have the auto-scrolling on by default.

**Comment by lieut-data** [comment]
Thanks for the extra context, @carlspring -- cc @sudheerDev & @esethna re: autoscrolling configurability.

**Comment by carlspring** [comment]
Just to clarify -- this also happens when you're actively chatting **in the same window/tab**.

**Comment by esethna** [comment]
@sudheerDev if the user is at the bottom of the channel it would be expected to keep the user at the bottom in all cases, wouldn't it?

**Comment by sudheerDev** [comment]
> @sudheerDev if the user is at the bottom of the channel (and doesn't leave the channel) it would be expected to keep the user at the bottom in all cases, wouldn't it?

I guess it is a combination of gnome, and the resolution + scaling. Amy created a ticket for investigation. Gonna be tricky to debug though

**Comment by carlspring** [comment]
Guys,

Has anyone had a chance to look into this? This is a massive usablitiy bug! It's probably the most annoying bug in a product that I have encounterd this year! I have no idea what you guys changed in recent releases and why this started happening, but it is so frustrating, it's becoming unbearble to use and I'm a really patient person.

**Comment by esethna** [comment]
@carlspring the bug is in our queue but hasn't been looked at yet unfortunately. To help in narrowing this down, what version were you using before v5.28.1?

**Comment by carlspring** [comment]
We were previously using `5.23`.

**Comment by esethna** [comment]
@carlspring thanks, I added this to the ticket

**Comment by tmuka** [comment]
Glad to see there's a ticket to address this behavior.  I have the same issue with conversation's not auto scrolling on Windows 10 using Chrome on a 15" 4k HDPI ThinkPad P1.  It's driving me crazy that even after I send a message I have to manually scroll down to see it, then if they send a reply I have to manually scroll down again!  

I'm not sure if it's related or not, but i'm connected via RDP to a desktop with a remote non-hdpi 4k 40" monitor via the hdpi laptop.

**Comment by carlspring** [comment]
Oh, this actually makes me so happy! I mean -- if someone else can reproduce it, then there's certainly something going on. I am experiencing exactly what you have confirmed! I am also on a 4K monitor. I am not connecting over RDP, or anything like that -- it's directly on my machine's web browser.

I am getting this issue all the time and it is simply driving me nuts!

Has there been any progress on this task? Could you please prioritize it? Thanks!

**Comment by tmuka** [comment]
I can confirm that it's happening to a few other of my teammates using 4k dell laptops on Windows 10 + Chrome too.

**Comment by carlspring** [comment]
Same here. Both my built-in (3840x2160) and external monitors are 4K (3840x1200). It's happening on both.

I'm only using Chrome as well, always the latest, as I'm a software engineer.

**Comment by carlspring** [comment]
It's been four months that this has been a constain pain in my ass. Could somebody please look into this? Having a 4K monitor isn't something all that exotic nowadays.

**Comment by hahmadia** [comment]
@esethna @lieut-data Any thoughts when this will be addressed?

**Comment by hmhealey** [comment]
Unfortunately, we still haven't been able to reproduce this issue on our end, so we haven't been able to work on this. As such, we're going to open it up as Help Wanted since we'd definitely appreciate help fixing this. Hopefully someone who is able to reproduce it will be able to take a shot at fixing it?

The only other advice I could think to give is that instead of being related to screen size, perhaps there's something causing the user to be moved far enough from the bottom of the channel that the keep-at-bottom logic is disabled. We used to have a recurring problem where content loading in posts (like images and attachments) would cause the height of a post to increase which pushed the bottom of the channel too far off screen. As far as I know, we've fixed all cases of that within the web app itself, but perhaps some has crept back in under specific circumstances or perhaps that's happening due to a plugin?

**Comment by Blackclaws** [comment]
This bug has recently started happening to me. I'm going to try and reinstall mattermost desktop as this is extremely annoying.

**Comment by carlspring** [comment]
This has been happening to me in a regular basis via the webapp. Surely more people must be encountering this! It is so frustrating! Could somebody finally look into it?!

**Comment by MichelGeorgy** [comment]
Happens to me and a colleague as well. 
Mac Desktop v5.1.0

**Comment by hmhealey** [comment]
To provide some visibility into this, we've been looking to this a bit again since it seems to have crept up again to be more frequent. We still don't have any good leads on what, in particular, is causing this, but it's on our radar since it seems to have started more frequently.

If anyone has any even anecdotal details about when it might be happening, please let us know. For example, it almost always happens to me in a specific DM channel, and I don't think I've seen it outside of DMs, but I believe other people have seen it elsewhere. Any consistent stuff like that might help point us in the right direction to get this fixed.

**Comment by tmuka** [comment]
possibly related, when pasting an image into mattermost, the chat frequently won't scroll down to reveal that the image has been successfully pasted, which can result in me pasting it multiple times since I didn't scroll down manually to see it was uploaded/pasted. this happens frequently both in channels, and in DMs, by myself and my co-workers. 

Mattermost Version: 6.5.0
Database Schema Version: 6.5.0
Database: postgres

**Comment by Blackclaws** [comment]
For me clearing cache has solved the issue for now

**Comment by alolis** [comment]
My team and I are experiencing the same issue with Version 5.1.0 (19937).

Please fix. This is very annoying.

**Comment by alolis** [comment]
> For me clearing cache has solved the issue for now

Can you please provide steps for this so I can give it a try?

**Comment by steve-todorov** [comment]
@hmhealey I was wondering if mattermost is storing the "scroll position" in the database? Maybe this happens due to sync issues between devices ? (i.e. you have 100 new messages, your mobile has read up to id 50, your web is at 80, but since your mobile is behind it overwrites the current position?) I've seen this issue on mobile as well, so this leads me to think it might be related to the state sync between devices? 

It looks like nobody knows when / how this happens. So if you could please share with us the flow of how the state persisting works and is synced between devices that might help? If there is something stored in the database maybe I could give some feedback the next time it happens. Other than that - it looks like this is happening randomly and I haven't had any luck with debugging it.

**Comment by hmhealey** [comment]
There's some state that's saved, but it's not storing it in the database exactly. The web app tries to load the app at the last message you've read, and it's storing where that's at, but that's just when you first view a channel. The mobile app always loads the channel at the bottom, and it has a toast that you can click to scroll up to the last message you'd previously read.

There's specific logic that's supposed to keep you at the bottom of the channel, but it's rather complicated because it needs to trigger not just when you receive new messages, but also if a message changes height (likely because some content was loaded or a post was edited), and this bug is likely in that logic. In the mobile case in particular, I think that's because the "A user is typing..." message pushes the user far enough from the bottom that this logic stops triggering (because we want it to not happen when a user is viewing older posts), but I haven't been able to find why it sometimes stops working on the web app.

**Comment by lieut-data** [comment]
@hmhealey, could we instrument some console debug messages in the relevant code, to the effect of "auto-scrolled X" or "not at bottom, skipping auto scroll", and somehow hidden behind a user-level feature flag (ala `window.LogAutoScrollEvents` or some such?

I wonder if we could recruit community help to fine tune this further based on the outcome of that logic?

**Comment by hmhealey** [comment]
I'll take a look at doing that if I can track down exactly what logic is responsible for that. Unfortunately, I think it's part of the forked infinite scrolling library that we have which hasn't been touched in a while, so I'll need to do some digging for it.

**Comment by movy** [comment]
Just upgraded my DESKTOP client (MacOS) and this drives me nuts -- I can see a notification, but if i'm in the same chat/channel, it MM scroll to the new messages, so it takes me some time to realize where exactly did the new message appear until I realize I need to scroll down to see it.

**Comment by lieut-data** [comment]
@movy, @hmhealey added some debug logging in https://github.com/mattermost/mattermost-webapp/pull/10603 that ships in the upcoming Mattermost v7.1. If you have a chance to upgrade, set the `window.logPostEvents = true` in your console, and then share some of resulting the `console.log` output, we might be able to learn some more about why this happens.

**Comment by steve-todorov** [comment]
@levb thats great! Is there any timeline for the new release?

**Comment by lieut-data** [comment]
@steve-todorov, v7.1 releases tomorrow 🎉.

**Comment by amyblais** [comment]
Closing an older issue - this can be re-opened if it still reproduces on the latest version.

**Comment by carlspring** [comment]
Hi,

This bug is back and it's gotten terribly bad! Like so goddamn annoying! Someone sends you a message, you're looking at the same channel -- you have it open in front of you. Whether you're typing a new message, or just looking at the screen while someone else is typing -- it makes no difference.

# IT JUST DOESN'T AUTOSCROLL.

You then have to refresh the page or just scroll down yourself.

This bug has been around for like five years now. It goes away and mostly comes back.

Could you please look into this?

It's happening for me and my brother under Chrome (Version 145.0.7632.159 (Official Build) (64-bit)) + Ubuntu (Ubuntu 24.04.4 LTS).

```
Server Version: 11.4.0
Database Schema Version: 149
Build Number: 21550760092
Database: postgres
```

Many thanks in advance!

**Comment by hmhealey** [comment]
Thanks for the report. We're aware of the issue. Something has changed recently, and I'm trying trying to sort out why it's gotten worse recently and how to hopefully prevent this from reoccuring in the future

**Comment by carlspring** [comment]
@hmhealey ,

If you need us to test a snapshot, let us know. There are two of us who can constantly reproduce it.

cc: @steve-todorov

**Comment by steve-todorov** [comment]
I confirm -- this has been reappearing all the time. I would be happy to provide logs and or any other information that might help as long as there are some pointers on how to collect it.

**Comment by dankykang331** [comment]
I have the same issue and it's driving me crazy. Makes no difference if I use the webui or the app, same problem on 2 different Macbooks.

**Comment by steve-todorov** [comment]
@dankykang331 what I've noticed is that it seems to go away if you resize the window to a lower size (i.e. if it was maximized -- unmaximize it and the scrolling starts to work again) . Still a problem though. Not sure why this ticket is still closed.

**Comment by lieut-data** [comment]
@hmhealey, I think this is related to a new issue you were looking at recently? Can you share details?

**Comment by carlspring** [comment]
For the record, why is this ticket closed, if it's not fixed?

**Comment by lieut-data** [comment]
@carlspring, it's probably that there's simpler a newer issue for when the regression was spotted. Our typical practice is not to resurrect old reports even if the symptoms are similar.

**Comment by dankykang331** [comment]
This was driving me so crazy that I just tried using Claude to fix it. It magically came up with a solution:

(function() {
      var lastHeight = 0;
      var el = null;

      setInterval(function() {
          if (!el || !document.contains(el)) {
              el = document.getElementById('postListScrollContainer');
              lastHeight = 0;
          }
          if (!el) return;

          var newHeight = el.scrollHeight;
          if (newHeight > lastHeight && lastHeight > 0) {
              var distFromBottom = lastHeight - el.scrollTop - el.clientHeight;
              if (distFromBottom < 400) {
                  el.scrollTop = el.scrollHeight;
              }
          }
          lastHeight = newHeight;
      }, 300);
  })();

It put this in root.html - every 300ms it checks if there's a new message and if there is, it scrolls down to the bottom if you're within 400px of the bottom. Vibe coded slop, yes - but it actually scrolls to the new messages now.

**Comment by carlspring** [comment]
@lieut-data ,

So, if it's being tracked under another issue, I think it would be more than reasonable to link it here and tell people where to be leaving the comments. Otherwise we might as well be shouting at the wind.

Is there any ETA for this? It is **_REALLY_** annoying and it's not a new issue. It's been something that comes and goes and is now back.

**Comment by lieut-data** [comment]
You're right, it is annoying. (Admittedly, I don't see it myself, but I remember this issue when it first happened.) I regret we don't offer public ETAs, but if you've got an enterprise license feel free to escalate for any information we can share internally.

As for linking, that's precisely whey I looped in @hmhealey in the hopes of more details and possibly a link to the other issue.

**Comment by carlspring** [comment]
Okay, that makes sense. Thanks for clarifying this.

**Comment by carlspring** [comment]
Any idea if this bug will ever get fixed?
At this point I can safely say this is absolutely the most annoying bug about your server.

**Comment by hmhealey** [comment]
@carlspring Which version of Mattermost is your server running now? It should be fixed in 11.7.0, 11.6.1, and 11.5.2. It also affected 11.4.x and 11.3.x releases as well, but those were out of the support window by the time we were able to fix it

**Comment by dankykang331** [comment]
@hmhealey 11.7.0 - still has the same problem

**Comment by steve-todorov** [comment]
Please move the discussion into #37670 -- this ticket is closed, so probably won't get attention.
