### ISSUE TITLE
Text copied from Microsoft OneNote pastes as an image

### ISSUE THREAD

**Issue by shieldsjared** [mattermost/mattermost#16858]
#### Summary
Text copied from Microsoft OneNote pasted text as image.

#### Steps to reproduce
- Open Microsoft OneNote
- Write a note (can even be simple text with minimal formatting)
- Copy the note into your clip board
- Paste into Mattermost (desktop or web)

#### Expected behavior
- When pasting, the data in the clipboard would paste as text (if possible).

#### Observed behavior (that appears unintentional) 
- The entire text is pasted as an image (as if a screenshot) from OneNote

Note: This was not an issue in MM v5.25. Recently updated to v5.31 and now experiencing this. Our workaround is to copy/paste from MS OneNote -> MS Word -> Mattermost. Users are on Win 10 OS, and issue can be observed when using both the browser or desktop client.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-32576

**Comment by david1170** [comment]
I'm also having this problem, pasting from Word, Excel using a Mac.  It doesn't seem like it's been resolved and I'm wondering what is the status?

**Comment by amyblais** [comment]
I don't have specific status updates, the Jira ticket is in one of our dev team's queue.

**Comment by david1170** [comment]
Is there a way to find out the status?  The original request appears to
have been made in Feb of this year.
Thanks,
David

**Comment by Skogsuggla** [comment]
I'm also highly interested that the problem will be solved fast. Working a lot with Mattermost and OneNote...

**Comment by hmhealey** [comment]
I'm going to open this up as Help Wanted. We haven't been able to prioritize this at any point, but perhaps someone from the community will be able to fix this.

If I had to guess, the paste handler in the FileUpload component sees a file of some sort in the paste event, and it handles it while preventing the text from being pasted. I'm not sure if there's anything in that event that tells us what the app prefers to paste (to either prioritize the image or to prioritize the text) that we could look at for this. I seem to remember copying and pasting images sometimes also brought along text with them which might be the logic that's causing this problem.

**Comment by kalevnakah** [comment]
Based on the below article, MS Office simultaneously puts the text and picture versions of the text in the clipboard. The Mattermost app has to determine whether to grab one or the other or both. I think that you would have to change the app to do both and then delete the image, otherwise pasting pictures with text, would leave the picture behind. 

Alternatively, the users need to be educated to use "Shift + Ctrl V" instead, which only pastes the text. This could be added to FAQ or Troubleshooting document somewhere. I didn't verify it works on Mac, but windows work fine.

Personally from an end-user perspective, I would rather hold shift, than have to delete an image every time. And I don't think I would want to risk not being able to paste an image, because it has text attached. Up for discussion?

https://answers.microsoft.com/en-us/msoffice/forum/all/copy-and-paste-from-onenote-as-an-image-not-text/d77148a4-eef7-4940-aa8b-f56b610d5ebb

**Comment by shieldsjared** [comment]
Had no idea that `Shift + Ctrl + V` was a thing! Great insight @kalevnakah!  Personally I don't have an opinion on a good fix for it. But if I had to weigh in, using the key combo you've shared seems like the most flexible, so I agree that it would just be a matter of educating users. Or perhaps I'm just _really late_ to the game on that shortcut.

**Comment by kalevnakah** [comment]
I have been a power user of computers for the last 25+ years and never knew about this until yesterday and I think it's a really well-kept secret. Especially considering how old this issue is and I am the first to mention it here.

I think my theory about how the 'copy and paste' works, is wrong. I just tried copying different things from one note and other sources and pasting them into Evernote and this GitHub comment box. Those apps seem to handle text and images properly, so there must be a proper solution without compromise.

**Comment by hmhealey** [comment]
Interesting. I didn't know that was supported by the browser. I figured that would be something we'd need to implement ourselves. It doesn't seem to disable all of our paste handling, but at least it works for this case

**Comment by hmhealey** [comment]
Echoing my comment from the PR here, for everyone on this issue, would you prefer if this always pasted as just text or as an image with text? I don't use OneNote, so I don't know what would be preferred here since I could see pasting as an image being ideal if you copy a note that's more than a single piece of text.

I compared against some other apps, and Slack always pastes text while Discord always pastes an image

**Comment by PlaneNuts** [comment]
> 

Personal, and the reason I subbed to this issue was because other's felt the same, I think pasting as text is best

If I want an image, I'll use greenshot to grab an image of the note

In my case, it was tables from Excel being pasted as an image, SUPER annoying, but really for any format, if I'm copying text, I want text pasted. If I want an image, there are other tools to easily make that and paste an image

**Comment by Skogsuggla** [comment]
I feel the same as @PlaneNuts wrote. Maybe if the functionality is already there, why not offer it when "right-clicking"?
Standard should be pasting as "text"/value and if I like, I could use "paste as picture" from the menu (right-click).
