### ISSUE TITLE
Adding a mention can clear the message box and erase the undo history

### ISSUE THREAD

**Issue by hjek** [mattermost/mattermost#17130]
#### Summary
Adding a mention can clear the message box and erase the undo history

#### Steps to reproduce
First I compose a good long message. Then, I decide I want to add an at-mention at the start, so I move the text cursor to the very beginning of the message and type "@" and a username drop-down appears. Now, while this drop-down is visible, if I accidentally press either `←` or `→` once causing the text cursor to move, and then select a username from the drop-down, then — **BAM!** — everything after the text cursor is gone, which in this case is the entire message (and the selected username isn't inserted either). Even worse, `CTRL + Z` to undo does *nothing*, because (and perhaps this should be considered a second bug) the entire undo history is erased when clicking on a username from the drop-down.

#### Expected behavior
I'm expecting Mattermost to not delete the messages I'm composing, and *if* they're deleted, then I expect undo to be available.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-33823

**Comment by achalagarwal** [comment]
@amyblais I can see a similar regression in `Mattermost Version: 6.7.0`

I am not sure how to reproduce it (its not the same way as listed in the OP) but the after effects are the same i.e.:
1. Everything after text cursor is deleted
2. Undo History isn't there (more specifically Ctrl-Z doesn't work)

**Comment by jmasukawa** [comment]
@amyblais Any idea for prioritization / timeline of a fix? This is a pretty frustrating experience for our organization.

I can confirm this issue is still occurring consistently on: `Mattermost Version: 7.7.0`.

Repro info (note: a lot is overlap or c/p from OP, but figured "how this happens in 2023" couldn't hurt):
1. Carefully wordsmith a long message.
2. Then, I decide I want to add an at-mention somewhere (ex: front of message), and type "@", and a username drop-down appears.
3. While this drop-down is visible, I accidentally move the cursor location: pressing either ← or →, a mis-click with the mouse or accidentally touch my laptop touchpad with my fat sausage fingers, etc.
4. I eventually select a username from the drop-down, then — BAM! — everything after the current position of the text cursor gets deleted.
5. CTRL + Z to undo does nothing, because (and perhaps this should be considered a second bug) the entire undo history is removed when clicking on a username from the drop-down, even in normal message composition behaviors.

Gif below shows two user journeys:
- The normal use case where the cursor position stays the same throughout steps 2-4 (this is the working case)
- The buggy case where the cursor position changes after the "@" mention menu is open, and all text after the cursor position is deleted.

![mm_message_content_deleted](https://user-images.githubusercontent.com/1621643/218586191-d1ca0226-9efd-4d91-bd91-ff5325eae6cb.gif)

**Comment by amyblais** [comment]
There is a PR in progress for this by one of our devs @koox00 -- https://github.com/mattermost/mattermost-webapp/pull/9906.
