### ISSUE TITLE
Unsafe character colon used in pasted file name

### ISSUE THREAD

**Issue by t-tsutsumi-scc** [mattermost/mattermost#17240]
#### Summary

When the interface language is set to Japanese, a colon (`:`) is included in the file name pasted from the clipboard. A colon cannot be used in file names on Windows.

#### Steps to reproduce

1. Start a new instance of the latest Mattermost.
    ```bash
    docker run --name mattermost-preview -d -p 8065:8065 --add-host dockerhost:127.0.0.1 mattermost/mattermost-preview
    ```
2. Access Mattermost with a web browser and change the interface language to Japanese.
3. Paste an image from the clipboard and post it.
4. You can see that the uploaded file name includes a colon(`:`).
    ![uploaded-file-name-includes-colon](https://user-images.githubusercontent.com/75708205/112658059-607d6000-8e96-11eb-93be-ab54fada199b.png)

#### Expected behavior

The file name generated by Mattermost should consist of characters that can be used in common operating systems and file systems. IMHO, The file name should not depend on the interface language.

#### Observed behavior (that appears unintentional) 

See above.

#### Possible fixes

As with zh-TW, use Fullwidth Colon`：`(U+FF1A) instead of  Colon`:`(U+003A) in Japanese (ja).

https://github.com/mattermost/mattermost-webapp/blob/master/i18n/ja.json#L2777

```diff
diff --git a/i18n/ja.json b/i18n/ja.json
index e62792c8e..3aa6798fe 100644
--- a/i18n/ja.json
+++ b/i18n/ja.json
@@ -2774,7 +2774,7 @@
   "file_upload.generic_error": "ファイルのアップロード中に問題が発生しました。",
   "file_upload.limited": "同時にアップロードできるのは{count, number}ファイルまでです。これ以上アップロードするには新しい投稿をしてください。",
   "file_upload.menuAriaLabel": "アップロードタイプ選択",
-  "file_upload.pasted": "画像の貼り付け先: ",
+  "file_upload.pasted": "画像の貼り付け先：",
   "file_upload.upload_files": "ファイルをアップロードする",
   "file_upload.zeroBytesFile": "空のファイルをアップロードしようとしています: {filename}",
   "file_upload.zeroBytesFiles": "空のファイルをアップロードしようとしています: {filenames}",
```

Note: I don't understand the impact of this change on past posted images.

**Comment by amyblais** [comment]
@t-tsutsumi-scc Translations are done via the translations server https://translate.mattermost.com/. Let me know if you're open to submitting a translation edit. Or let me know if I misunderstood this report.

**Comment by t-tsutsumi-scc** [comment]
@amyblais
I think the root cause of this issue is not the error in the translated text, but the Mattermost features and translation rules.

1. The translated text of `file_upload.pasted` key is used for the file name when uploading an image from the clipboard. Is it clear that there are characters that should not be used in this translated text, such as a colon? IMHO, Mattermost should escape this translated text so that it can be used as a file name.
2. Does changing the translated text of `file_upload.pasted` key affect previously uploaded images?

@kaakaa (Japanese translation official reviewer)
Do you have any opinions?

**Comment by amyblais** [comment]
Thanks, created a ticket: https://mattermost.atlassian.net/browse/MM-34355

**Comment by t-tsutsumi-scc** [comment]
Whether a file with a file name with a colon can be read or written on Windows is implementation-dependent. As a practical matter, a backup software may not be able to access the file. In other words, it is difficult to backup Mattermost (including users who use Japanese as the interface language) running on Windows.

I hope Mattermost team will address this issue. 🙏 

Ref: [Stack Overflow] How to get a file in Windows with a colon in the filename?
https://stackoverflow.com/questions/10386344/how-to-get-a-file-in-windows-with-a-colon-in-the-filename

**Comment by lieut-data** [comment]
@t-tsutsumi-scc, may I assume that the problem lies in the server writing to disk the name provided by the webapp in this case? Can you reproduce this problem by intentionally uploading a file with a colon (vs. the auto-inserted one in Japanese) and observe the same behaviour?

I'm inclined to ask the server team to harden our file interface on Windows to handle this either way, but want to understand the scope here.

**Comment by t-tsutsumi-scc** [comment]
@lieut-data
> may I assume that the problem lies in the server writing to disk the name provided by the webapp in this case?

Yes. Mattermost should use safe filenames regardless of platform (Windows, macOS, Linux...).

> Can you reproduce this problem by intentionally uploading a file with a colon (vs. the auto-inserted one in Japanese) and observe the same behaviour?

It seems to behave the same when manually uploading a file with a colon. (Interface Language: English)

After uploading:
![console-manual-upload-with-colon](https://user-images.githubusercontent.com/75708205/112940395-0f0bf400-9168-11eb-87d2-5fcc207156be.png)

Downloading the file on Windows (Windows 10 20H2 19042.867 / Google Chrome 89.0.4389.90):
![browser-manual-upload-with-colon](https://user-images.githubusercontent.com/75708205/112940383-0b786d00-9168-11eb-92c9-e23a20a8a3f0.png)

**Comment by lieut-data** [comment]
Thanks, @t-tsutsumi-scc! That helps clarify things tremendously :)

**Comment by kaakaa** [comment]
Thanks @t-tsutsumi-scc 
The translated string looks wrong, and I didn't notice this because we're not run Mattermost on Windows.
I can fix the translation soon, and it seems to work fine as far as I tried. However, changing the translation doesn't fix existing filename, so the problem of not being able to back up files on Windows still remains. It should be needed to migrate existing filename and data about post related to its files.

@amyblais @lieut-data 
I would like you to take into account when to fix the translation and how to fix the file names that have already been created with invalid filename. Thanks.

**Comment by lieut-data** [comment]
Thanks, @kaakaa! I don't think fixing the translated name is the right solution here, since the user can cause this problem by uploading a file directly vs. the drag and drop approach. (By all means, if the translation is wrong for other reasons, feel free to help fix that!)

I'll defer to our server team on the issue of legacy files uploaded as such, but we may prioritize with individual customers instead by helping them update the state of their database vs. building something directly in code.

**Comment by amyblais** [comment]
We are closing some older tickets that have been inactive for a while. If the issue persists on the latest server version, feel free to re-open this issue.
