### ISSUE TITLE
Invite email link is white on white background

### ISSUE THREAD

**Issue by narduin** [mattermost/mattermost#17605]
#### Summary
When inviting via email to a team, the link to join inside the email is white on a white background, making it really hard to join.

#### Steps to reproduce
- install Mattermost Team Edition 5.34.2
- create a team
- invite someone to the team via email

#### Expected behavior
The link to join should be visible and obvious.

#### Observed behavior (that appears unintentional) 
Tried on two different email clients, same white link.
![email](https://user-images.githubusercontent.com/20305403/117845576-fa4f6f80-b280-11eb-959f-2ecbaffe39f7.png)
![selected email](https://user-images.githubusercontent.com/20305403/117845586-fcb1c980-b280-11eb-91d3-7f311214261c.png)

#### Possible fixes
I inspected the invite email template [here](https://github.com/mattermost/mattermost-server/blob/master/templates/invite_body.html)
I don't know if that's it but line [398](https://github.com/mattermost/mattermost-server/blob/c90c371fd4016345e4fcc2c619d3b5c47edaeecc/templates/invite_body.html#L398), the button has `style="background:#FFFFFF;color:#ffffff;"`
Changing the color to black resolved this on my server.

**Comment by narduin** [comment]
> Opened a ticket: https://mattermost.atlassian.net/browse/MM-35631

Thank you!

I tried signing up on an "open server" configuration and the validation email has the same problem.

**Comment by hahmadia** [comment]
Hi @narduin,

Mattermost Developer here!

So I took a look into this and the email I'm receiving is vastly different from yours. 
![image](https://user-images.githubusercontent.com/17804942/118009629-3683de00-b31c-11eb-873f-200356f868e9.png)


Notice all the styling that is in my email and not yours. My gut tells me that your client may be stripping the HTML parts as part of some sort of security measure. If your email client allows you too, you can view the email as plain text to avoid this problem.

![image](https://user-images.githubusercontent.com/17804942/118009879-79de4c80-b31c-11eb-95bc-4a597e26e470.png)

Could you try inviting someone with a gmail email and reporting back if they get the same problem? 
I tried everything on my end and wasn't able to reproduce which is why my suspicion points towards email client and not Mattermost.

Thanks!

**Comment by narduin** [comment]
Hello @hahmadia!

I investigated further into email clients. It is indeed where the bug occurs.

I noticed that a lot of the styles, including the big "join team" button, are declared as css rules inside a `<style>` tag.
Support for `<style>` element [is still partial](https://www.caniemail.com/features/html-style/) within email clients.

That is why I can't see the button in **ProtonMail, Tutanota and Rainloop** for example. I can see it with gmail and outlook because they support some external css rules.

I think this could be corrected with inline styles as a fallback like my fix here:
>  Changing the color to black resolved this on my server.

I would have tested further but I don't know how your email templates are compiled together.

**Comment by amyblais** [comment]
@narduin It seems that our email templates don't yet support clients that don't support the <style> tag. Would you be open to sharing this request on our ideas forum here https://mattermost.uservoice.com/forums/306457-general?

**Comment by narduin** [comment]
I will share the idea but it feels more critical than just a feature request. It's a huge accessibility and user experience problem.
Ultimately, it may lead to users being unable to join teams or at least having trouble joining.

I will try on my server to create the fallback styles inside the .mjml templates and keep you posted.

**Comment by narduin** [comment]
Successfully converted `css-class` styles from external classes to inline `mj-class` styles and it shows up correctly in my client!
![image](https://user-images.githubusercontent.com/20305403/118694112-018bf580-b80c-11eb-9b4a-8dcf273b89e4.png)

**Comment by hahmadia** [comment]
@narduin 

Feel free to open a PR request. I'm a developer and can't decide on the priority of features. If you feel this is critical, you can open up a PR and our team will look at it and merge in due time. Thanks for your understanding and investigation. We look forward to your contributions!

**Comment by amyblais** [comment]
I created an improvement ticket also https://mattermost.atlassian.net/browse/MM-35847.

**Comment by narduin** [comment]
> Feel free to open a PR request. I'm a developer and can't decide on the priority of features. If you feel this is critical, you can open up a PR and our team will look at it and merge in due time. Thanks for your understanding and investigation. We look forward to your contributions!

I would love to but I'm only a front-end developer and I don't know a lot about docker and back-end technologies.
**However**, I found a quick-fix that made the emails show up correctly on both my "non-supported" email clients.

Given that you use [one partial](https://github.com/mattermost/mattermost-server/blob/master/templates/partials/style.mjml) to define the styles with classes, adding [the inline attribute](https://mjml.io/documentation/#mj-style) to its [style tag](https://github.com/mattermost/mattermost-server/blob/abdba7acc3c74cb8672c45fbe60c5955c9268fa2/templates/partials/style.mjml#L10) resolves most of the non-supported problems (I did not check all the templates):

```html
<mj-style inline="inline">
...
</mj-style>
```

The only downside that I saw is that you loose some styling (like rounded corners on buttons). Such styling is preserved when you convert **css-class into mj-class** though.

**Comment by esethna** [comment]
@narduin really appreciate your work here and raising this with us. Agree this is pretty critical functionality. 

@amyblais can you help get this routed to the appropriate team with high priority, probably the Growth team. 

https://mattermost.atlassian.net/browse/MM-35847

**Comment by narduin** [comment]
@esethna thank you, I would be happy to help your team in any way I can.
I can provide the converted mj-classes, I'm sorry I couldn't integrate them on a PR on my end.

**Comment by gabriel-vasile** [comment]
Hi, I encountered [this issue](https://github.com/mattermost/mattermost-server/issues/18242) too and I can confirm the fix from @narduin works.
> ```
> <mj-style inline="inline">
> ...
> </mj-style>
> ```
> 

I can start a PR with his change. I think it's also good to add a footnote in the email, something along the lines of:
_If you experience any issues with the button above, copy and paste the URL below into your web browser._

But before I do any of that, it seems like the mjml and html in ./templates are out of sync. Running
```bash
./scripts/diff-email-templates.sh
``` 
outputs a whole lot of diffs.
Could this be because of my local install of mjml generating some different html or indeed they are out of sync?
