### ISSUE TITLE
Playbook Plugin failed to start. "failed to run migrations[...]"

### ISSUE THREAD

**Issue by LukasFiniarel** [mattermost/mattermost#18666]
#### Summary
After upgrading from Mattermost 5.39.0 to 6.0.0 the newly added Playbook plugin is unable to start.
The system-log gives the following error:

`
{"timestamp":"2021-10-13 09:58:19.029 +02:00","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:146","plugin_id":"playbooks","error":"failed to run migrations: failed to complete migrations: error executing migration from version 0.10.0 to version 0.11.0: failed updating table IR_Incident with Channels' CreateAt and DeleteAt values: Error 1267: Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='"}
`

The Linux-Server runs with MySQL Version 8.0.25

**Comment by lieut-data** [comment]
Thanks for the heads up @jasonblais! @LukasFiniarel, can you help with a few extra details?
* May I assume you are running against MySQL? Can you share the version in question?
* Did you have Playbooks (previously called Incident Response) enabled at some point in the past, but disabled prior to upgrading? The migration version in question is very old (from March of this year), so I'm assuming the product has not been running since then given you were running `v5.39.0` very recently.

My team will probably have more questions soon :)

**Comment by lieut-data** [comment]
@LukasFiniarel, I don't /think/ the default collation change is required there, but I admit I'm not 100% confident. I believe the reason the `utf8mb4_0900_ai_ci` was effectively the default was because of the `SqlSettings.DataSource` connection string we recommend making the character set of `utf8mb4` explicit (and thus the corresponding default collation). MySQL sure is complicated :D
