### ISSUE TITLE
Text followed immediately by a table causes the table not to be rendered

### ISSUE THREAD

**Issue by Andrew-Cole2** [mattermost/mattermost#19133]
#### Summary
Mentioning a user at the beginning of a message causes some formatting rules to not be applied.

#### Steps to reproduce
Mattermost v5.26.0/v4.6.2

#### Expected behavior
Mentioning a user at the start of a message followed with text formatted to be a heading or table will cause the formatting to not be applied.

If user is mentioned elsewhere in message formatting does not break.

Issue was able to be reproduced in Mattermost version 5.26.0 and version 4.6.2 in public channel, private channel, and direct messages.

Issue only occurred when using heading and/or table formatting
Issue does not occur with most other formatting (bold, italics, code, and lists) but did not test all format options

#### Observed behavior (that appears unintentional)
Both message contents are the same with the exception of the mentioned user.
![MM formatting issues](https://user-images.githubusercontent.com/53118334/144920922-b5a2c405-0d60-463e-8808-a3733f057177.PNG)

**Comment by amyblais** [comment]
@Andrew-Cole2 Are you able to reproduce this on more recent versions? We support server version 5.37.0 and later, and the latest desktop app version is v5.0.

You can also optionally do some testing on our [community server here](https://community.mattermost.com/), which is on the latest version.

**Comment by isacikgoz** [comment]
I can confirm this is also reproduces on community server. Created the ticket: https://mattermost.atlassian.net/browse/MM-40557

**Comment by hmhealey** [comment]
To add a bit more detail here, this is happening because due to Markdown's weird paragraph continuation rules, the first 4 lines of that message are being treated as a paragraph even though there's a line break. A header followed by a table renders the table correctly, but the text at the start of that line is causing the first part of the message to be a regular paragraph instead which is preventing the table from rendering

So 
```markdown
any text at all
| aa | bb |
|---|---|
| cc | 11|
```

any text at all
| aa | bb |
|---|---|
| cc | 11|

works on GitHub, but not in Mattermost

![Screen Shot 2022-01-11 at 9 45 49 AM](https://user-images.githubusercontent.com/3277310/148964292-bae131f2-7f32-43a7-b02f-893e88703d22.png)
