### ISSUE TITLE
Add support for Google Cloud Storage

### ISSUE THREAD

**Issue by icelander** [mattermost/mattermost#19776]
#### Summary
Add a Google Cloud Storage filestore

#### Steps to reproduce
1. Set up a Mattermost instance with Minio as a proxy for GCS
2. Realize that Minio is dropping support for GCS

#### Expected behavior
There's an option to use GCS System Console alongside local and S3 > File Storage and you can use that instead

#### Observed behavior (that appears unintentional) 
Minio tries to delete the contents of your bucket

#### Possible fixes
Use [Google's golang library](https://cloud.google.com/go/docs/reference/cloud.google.com/go/storage/latest) as a basis for replicating the S3 filestore

**Comment by Yzzzi** [comment]
So i was trying to set up my mattermost with GCS s3 compatible storage, but no luck. Bumped into the fact, that minio proxy is deprecated too. 

Actually, when i insert credentials for my bucket into file storage settings tab - it shows, that `Connection was successful`, but actually continues to use local storage driver it seems, because bucket stays empty. Couldn't find any errors about it in logs.

![image](https://user-images.githubusercontent.com/18336586/173234500-7975d155-be6a-44a8-922f-3ff9e9859839.png)

Looking forward to use gcs bucket with mattermost natively! For now i am considering just switch to Amazon, or setup old minio version with proxy.

**Comment by nicolas-goudry** [comment]
Thanks @Yzzzi for reporting that the GCS S3-compliant storage is not working with Mattermost so I don’t have to test it. @amyblais IMO this is not a feature, it’s a bug on Mattermost side with its S3 implementation… Other providers are compliants with the S3 API so it _should_ work with GCS.

In the meantime, I’m also using an old version of MinIO GCS gateway because I don’t want to setup a full MinIO distributed cluster just to provide storage to Mattermost… As far as I know, the GCS gateway support was removed on Apr 26, 2022. Therefore, the last release supporting it should be the [RELEASE.2022-04-16T04-26-02Z](https://github.com/minio/minio/releases/tag/RELEASE.2022-04-16T04-26-02Z) with its [matching docker image](https://hub.docker.com/layers/minio/minio/minio/RELEASE.2022-04-16T04-26-02Z/images/sha256-a4102ef9c978ef4a164dde882b28534ed9779edf6dfc2e120f69a3abe9666941?context=explore).

Looking forward to see this fixed !

**Comment by agnivade** [comment]
@nicolas-goudry - As you have correctly identified, we use the minio library and minio doesn't support GCS properly. To add support, we need to add a separate GCS implementation of the filestorage API.

**Comment by chanukya-y-0086** [comment]
@mattermost/server-platform @mattermost/web-platform
any update on this feature or any workaround for this issue

**Comment by agnivade** [comment]
We do not support GCS at the moment, and there are no plans to support that in the near future. Our recommendation would be to use AWS S3 as the officially recommended storage layer.

**Comment by abourget** [comment]
Seriously? All of those deployment options, only to realize we're tied to AWS?
