### ISSUE TITLE
Unread thread when none exists

### ISSUE THREAD

**Issue by dstathis** [mattermost/mattermost#22060]
#### Summary
Unread thread count is 1 when none exists.

#### Steps to reproduce
Not sure how to make this happen. I am using 7.1.4.

#### Expected behavior
Unread count should not show up when everything is read.

#### Observed behavior (that appears unintentional) 
As can be seen in the screenshots, I see 1 unread on "threads" on the left and on the browser tab. (I use Mattermost through the browser) Yet when I go to see the unread thread there is nothing there.

#### Possible fixes
-
![unread_thread_tab](https://user-images.githubusercontent.com/2110777/212051858-dd243556-8a1e-445c-ad46-ba23faf6b783.png)
![unread_thread](https://user-images.githubusercontent.com/2110777/212051864-005cbe15-0efd-4402-8e5a-47f09b3d131e.png)
![no_threads](https://user-images.githubusercontent.com/2110777/212051868-6ded57f3-e9f7-42bd-9f14-4215e0c7cea8.png)

**Comment by amyblais** [comment]
@koox00 @Willyfrog Do you recall if this was fixed?

**Comment by koox00** [comment]
We haven't. There is a Jira ticket https://mattermost.atlassian.net/browse/MM-45802

**Comment by iprok** [comment]
The same problem. How can I reset the count?

**Comment by thorol** [comment]
Also same problem here. How can I reset it? Can I reset it in database or how can I see what is unread?

**Comment by jonasjancarik** [comment]
Also happening to me - Mattermost Version: 7.9.1

![image](https://user-images.githubusercontent.com/2459191/226292524-9872cea6-6106-46aa-958e-c06aa00a33fb.png)

**Comment by thorol** [comment]
I thought it was the feedback bot. För me it was fine after a while.

**Comment by Nick-Su** [comment]
Same problem too. I've managed to reproduce it in this way:

Preface:
User A (Collapsed Reply Threads is ON)
User B (Collapsed Reply Threads is OFF)

User A uses web browser or desktop app
Messages are written in the direct messages

Steps to reproduce:
1. User B writes a message №1 to User A (let's say the message 'msg1')
2. User B writes a message №2 to User A (not in the thread!)
3. User B creates a reply (message  №3) on the thread of the message №1 (let's say "msg3")
4. User B deletes message №3 (msg3)
5. User B creates a reply (message  №4) on the thread of the message №2 (let's say "msg4")
6. User A opens a desktop or a web client and reads the messages.

Expected behavior:
User A sees an unread notification and able to see messages №1, №2, №4. No more unread notification.

Observed behavior:
User A sees messages №1, №2, №4 and unread thread count is 1 when none exist. The unread tab is empty
If the user A opens a mobile app he can see message №3 (at least in a push notification), and the unread count resets.

Therefore, for me, using the mobile app (and tapping on the unread tab or highlighted messages) is a workaround.

**Comment by DDorch** [comment]
I've just enabled collapsed reply and I'm also facing this issue (Mattermost v7.8.3).

This bug makes the whole collapsed reply unusable since it's no more possible to see if there is a notification, actually. Is there anyway to reset this indicator?

I experienced this feature without any problem on another server and this is a nice feature anyway :)

**Comment by amyblais** [comment]
@Willyfrog @koox00 Do you know if there is a manual way to make the unread notification go away?

**Comment by Willyfrog** [comment]
The manual way is to click on the button to the left of the unreads tab (3 lines with a checkmark).
if the button is disabled you can mark one thread as unread (go to all threads, and alt-click on a reply or use the post menu to mark it as unread) so it enables.
Once you click on that one, it should reset the state.

**Comment by DDorch** [comment]
Thanks @Willyfrog ! You save my day with this workaround !

**Comment by DDorch** [comment]
Actually, this bug is noticed in the documentation: https://docs.mattermost.com/channels/organize-conversations.html

> When enabling Collapsed Reply Threads for the first time, you may see channels or threads you’ve seen before appear as unread. To resolve this, navigate to any unread channel, or select the Mark all as read button in the Threads view to mark all of your threads as read.
