### ISSUE TITLE
Uploaded files aren't deleted from the filesystem after file was deleted in chat

### ISSUE THREAD

**Issue by c0deright** [mattermost/mattermost#22343]
#### Summary
When using local storage for uploaded files (images, etc.), the files remain in the data directory even after the uploaded file has been deleted from the chat.

#### Steps to reproduce
Server: Linux, version 7.7.1
Storage: Local

- Upload an image the a channel
- delete the uploaded file from the channel
- look in the filesystem and you'll see the file still being there

#### Expected behavior
- For security reasons, once a file was deleted from chat it should be deleted from the storage, too.
- Should apply to S3, too

#### Observed behavior (that appears unintentional) 
- Uploaded files are still in the filesystem on the mattermost server

#### Possible fixes
- Delete the file from the storage backend when it is being deleted from chat

**Comment by amyblais** [comment]
Would you be open to sharing these reports via [responsibledisclosure@mattermost.com](mailto:responsibledisclosure@mattermost.com)? Please see more on our Responsible Disclosure Policy here https://mattermost.com/security-vulnerability-report/.

**Comment by DSchalla** [comment]
Hi @c0deright,

Thanks for your report. Mattermost only performs soft deletes for both posts and files as an intentional design decision, allowing for recovery of any deleted information (e.g. forensics, user mistakes, compliance, ...) at a later point. We support permanent deletion for both using the Data Retention feature in our Enterprise Plan (See https://docs.mattermost.com/comply/data-retention-policy.html).

As alternative for permanent deletion, it would be currently required to pull deleted posts from the database with related files, and then perform the deletes manually. I'm happy to help explaining the structure of the file system and how to pull the right information for this.

Thanks,
Daniel

**Comment by c0deright** [comment]
Hi @DSchalla,

thanks for that info. The Data Retention feature as I understand it does cover all files, not only soft-deleted ones - is this correct?
What if I don't want to prune old (non-soft-deleted) files after X days but want soft-deleted files to be removed from the filesystem in a timely fashion? Would that be possible with the Enterprise Plan?

Have a nice weekend.

**Comment by DSchalla** [comment]
Hi @c0deright,

That's correct, good catch. I think so far we had no request for that feature to my awareness. For my context, what would be the primary motivation for the hard delete on file systems? Would you like to only delete the files but keep the database record or also delete the record in the database? Would the same apply to post record in the database?

There is no immediate way that comes to mind (in both free or enterprise), but just asking some exploratory questions to understand the goal better. 

Thanks,
Daniel

**Comment by c0deright** [comment]
Hi @DSchalla,

the use case is simple: We use mattermost to connect all our employees and sometimes it's necessary to share sensitive information (e.g. a screenshot with personal identifyable information) with colleagues and when the issue is resolved we might delete that file from the channel/chat and want to make sure no copy is kept on the server.

It's just the way we (as IT engineers) see the world: delete a file and it should be gone (yes I know about data forensics and possible data recovery of deleted files).

**Comment by marknelissen** [comment]
I have a similar need. We regularly clean-up channels that are no longer required. This is a design decision as well, since it guarantees that obsolete confidential information is not kept longer than required in the system (gdpr). However, there is no easy method to cleanup the associated files as well, since a simple time-based rule is not sufficient. As @c0deright needs, only files from channels that are no longer in the system should be removed.

The channel deletion is operated through mmctl, through a custom plugin we wrote, which looks if the external system still references the channel, and if not, the channel is removed. As such, it would be acceptable that the cleanup command is tied to mmctl for us. The 2 solutions I can think of:

1. Include an option on the mmctl delete channel command to also remove the files
2. Add a separate command on mmctl to manage files, with the option to remove orphaned files

As it is now, we will probably have to write a custom lambda funtion that scans the entire S3 bucket, tries to match the files with the associated channels, and removes them. Not even sure if this is possible, there are alot of id's in the pathname of the files, so my guess is one of them is the channel id, however, this we still need to confirm.

**Comment by amyblais** [comment]
Hi @marknelissen, feel free to share feature requests on our Uservoice here https://mattermost.uservoice.com/forums/306457-general.

**Comment by marknelissen** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/46891111-mmctl-command-to-clean-up-orphaned-files

**Comment by amyblais** [comment]
Thank you!
