### ISSUE TITLE
Browser notifications broken in Firefox; user permission is never requested

### ISSUE THREAD

**Issue by aboukhal** [mattermost/mattermost#22976]
Tested in Firefox 102.8.0esr

Issue was tracked to the following code:
https://github.com/mattermost/mattermost-server/blob/5c8880321fc381b1398ed02a0f52462935017a73/webapp/channels/src/utils/notifications.ts#L54-L61

When Mattermost is not yet given the permission to send notifications, the value of `Notification.permission` is `default`. Instead of then asking the user for permission with `Notification.requestPermission()`, Mattermost incorrectly assumes that the user has disallowed them. This prevents any notification from being shown to the user.

Work-Around:
When entering `Notification.requestPermission()` in the browser's console while on the Mattermost page and then allowing the request, Mattermost will send notifications correctly from that point forward.

**Comment by amyblais** [comment]
Hi @aboukhal, what Mattermost server version are you on?

**Comment by aboukhal** [comment]
@amyblais It's version 7.9.2-rc1

**Comment by amyblais** [comment]
Thanks, opened https://mattermost.atlassian.net/browse/MM-52219.

**Comment by hmhealey** [comment]
Thanks again for the report! We addressed this in https://github.com/mattermost/mattermost/pull/26849 by adding a bar to prompt users for their notification permission when they first log into MM instead of waiting for when they would first receive a desktop notification. Hopefully this should fix some notification issues since we've recently found a surprisingly large number of users of even our community server haven't given notification permissions to the app
