### ISSUE TITLE
Blurred images on kubernetes deployment

### ISSUE THREAD

**Issue by carlmacdiarmada** [mattermost/mattermost#23789]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Bug report in one concise sentence
Pod has been evicted/restarted a couple of times, but images are showing as blurry before the pod came back up

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
latest docker image, pvc, screenshot posted into messages, restart pod/forcibly evict it

#### Expected behavior
Describe your issue in detail

![image](https://github.com/mattermost/mattermost/assets/5928593/7240cdf2-c229-491b-8bc8-7f15fb540f17)

I have a pvc attached via helm, so I'm not sure why this is happening?

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53238.

**Comment by gabrieljackson** [comment]
@carlmacdiarmada checking in here to see if you are still having issues with your deployment.

Based on your description, it looks like Mattermost no longer has access the the volume used to initially store the file attachments. Depending on your k8s cluster configuration this can occur at times. Often the volume that Mattermost initially used is no longer accessible for some reason. This can be due to Mattermost running on different nodes or general health issues with the underlying volume. I am assuming you are using a local volume, but let me know if that isn't the case. Using `kubectl` to review your k8s resources should reveal what is happening here. The one thing I can say is that blurred images are what is encountered when the underlying filestore files can't be accessed for any reason.
