### ISSUE TITLE
Server regularly goes out of memory

### ISSUE THREAD

**Issue by scriptdealer** [mattermost/mattermost#23872]
#### Summary
Memory consumption of a self-deployed server does not go to initial values at night times (at zero load). Server goes out of memory more and more often as users count grow.

#### Steps to reproduce
We have Mattermost: 7.10.2 TE over CentOS Linux release 7.7.1908 (Core)
Server have 6 CPU cores, 32 Gb RAM, and PostgreSQL
6k users

#### Expected behavior
Memory consumption of a self-deployed server should go to initial values at night times (at zero load).

#### Observed behavior (that appears unintentional) 
![image](https://github.com/mattermost/mattermost/assets/20861730/3f68da8e-09fc-41a4-8010-85f936523a95)
As you can see, memory use constantly grows, and it took nearly 5 days until server goes OOM (June 24 and 25 are weekend days and there were no growth). We managed to take heap profile just before OOM, and here it is:
[heap_at_oom.zip](https://github.com/mattermost/mattermost/files/11878934/heap_at_oom.zip)
Top user is (*WebSocketEvent) precomputedJSONBuf()
![alloc_space](https://github.com/mattermost/mattermost/assets/20861730/df117cb0-a692-4f65-be8b-76c14cdc8c06)

#### Possible fixes
There is cache invalidation handler, `/api/v4/caches/invalidate` and I hope it could be reworked so it can really drop all caches, precomputed JSONs, and other major memory users, maybe bleve ? Now calling this handler only drops memory use by 100-200Mb, though user's cache alone is above 1Gb.
There is a hope that calling this invalidation at nights will keep memory use under control.

**Comment by scriptdealer** [comment]
Also, `pstree` command shows that there are 200+ child processes after a few days, though at start-up time these are 20+
![image](https://github.com/mattermost/mattermost/assets/20861730/08603ae7-85c5-43d3-a1d8-3cdd3ef664ec)

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-53366.

**Comment by agnivade** [comment]
@scriptdealer - This seems like the same issue you filed earlier at https://github.com/mattermost/mattermost/pull/22465 right?

**Comment by agnivade** [comment]
@scriptdealer - Are you running high values of GOGC or GOMEMLIMIT by any chance?

**Comment by scriptdealer** [comment]
@agnivade True, this is a continuation of the same problem. since it becomes more and more demanding to be solved. As of GOGC and GOMEMLIMIT, I highly doubt our devops uses it. I'll go and ask them to test it. What you can suggest, "GOMEMLIMIT=24000MiB" и "GOGC=75" ?

**Comment by agnivade** [comment]
I'll suggest to start off with `GOGC=50`. If this still doesn't work, we can start tuning other variables.

**Comment by scriptdealer** [comment]
Seems like even setting "GOMEMLIMIT=16000MiB" and "GOGC=75" took RAM consumption under control, closing for now. Many thanks!
![image](https://github.com/mattermost/mattermost/assets/20861730/b3a80572-92f8-47eb-8a30-55877eb8032e)

**Comment by scriptdealer** [comment]
Damn it, need to reopen. It still seems that unloading part of heap steadily grows, and after going above mem limit GC calls are hitting CPU. This is with GOMEMLIMIT=10GiB () and GOGC=50:
RAM:
![image](https://github.com/mattermost/mattermost/assets/20861730/44afe5fc-58cf-43a9-a986-c37f9dbb1a74)
CPU:
![image](https://github.com/mattermost/mattermost/assets/20861730/845ca15e-2cc1-43e8-a39b-62218e5f593a)

**Comment by agnivade** [comment]
@scriptdealer - Since you are using the team edition, we don't have access to application metrics to look into what's happening inside the application to guide you better. I can only imagine that you have large messages being sent at a high rate to a large number of connected users. A stopgap measure that I can suggest would be to disable `ServiceSettings.EnableChannelViewedMessages` and `ServiceSettings.EnableUserTypingMessages`. These reduce the websocket events being transferred and should give more breathing room for your application. 

But without the Grafana metrics it's hard to understand what's happening here.

**Comment by scriptdealer** [comment]
@agnivade I think we could press the trial button, if that could help. Can you name these helpful metrics ?

**Comment by scriptdealer** [comment]
@agnivade Sorry for the delay, things went not as planned. First, immediately after upgrade our devops switched Bleve to Elastic. This has a dramatic effect on memory consumption:
![image](https://github.com/mattermost/mattermost/assets/20861730/58b9c326-d62f-4736-813b-2f901f424fc8)
So the first idea is that it was Bleve calls that leads to memory leaks. DevOps says we have 20+ mil messages, while Bleve is designed only for 2 (?). So could it be that indexing silently fails and that leads to misbehaving of websocket messages ?
Then, metric `broadcasts_total[5m] by (name)` you mentioned renders almost all message types as `other`:
![image](https://github.com/mattermost/mattermost/assets/20861730/1138a02f-365e-4b21-a73c-9b56937c6148)
I think with Bleve turned on it will display the same.
Nonetheless, memory goes up day to day, though at a **much** slower pace. It will take 2 weeks to hit MEMLIMIT, and more than month to try the OOM case. So one small question is, what is 'normal' memory usage ? Should it drop to the same values at every night?
And if we bring Bleve back, how should we filter related websocket messages ?

**Comment by agnivade** [comment]
From the heap profiles, it doesn't seem like anything to do with either Elastic or Bleve. The Grafana charts provided key information. It's this `other` messages which seem to be causing the high memory. 

If you can, could you please provide full screenshot of the entire panel for a 48 hr period for both 
- `sum(mattermost_websocket_broadcast_buffer_size) by (instance)`
- `sum(rate(mattermost_websocket_broadcasts_total[5m])) by (name)`

I want to compare the values with our production customers and see how large/small is the difference. 

Re: the `other` category, a lot of messages which are not categorized fall into this category. This is an improvement we have to address and explicitly categorize those events as well, because otherwise as of this moment, it's impossible to understand which event under the `other` category is causing the issue, if there is any.

**Comment by scriptdealer** [comment]
But seeing the graphs I can tell that with Bleve we had 6-8 Gb of growth per day, and with Elastic its 1-1.5 Gb. As for messages, here you go:
![image](https://github.com/mattermost/mattermost/assets/20861730/8db5855f-5d82-4272-bd84-198a5b6462d3)
![image](https://github.com/mattermost/mattermost/assets/20861730/f6f32942-6ff2-4ef6-b81e-d98aee4ed2f4)

**Comment by scriptdealer** [comment]
And one more graph bothers me now (off-topic), `Top 10 DB Calls by Count`
![image](https://github.com/mattermost/mattermost/assets/20861730/19a43200-1d76-42da-8320-6a000bc9b8b3)
is this alright that role calls eats up that much ?

**Comment by agnivade** [comment]
> But seeing the graphs I can tell that with Bleve we had 6-8 Gb of growth per day (up to 11), and with Elastic its 1-1.5 Gb. 

I mean, yes of course, Bleve is an embedded database which holds the data in-memory. Elastic is a different database altogether. So it's natural that memory consumption as a whole got reduced. But purely speaking from the heap profile, the allocations weren't coming from Bleve. 

So looking at your websocket broadcasts, your peak rates are around 10x higher than some of our large customers. This partly explains the high rate of allocations. But unfortunately, since a lot of events get bucketed into the `other` category, it's not entirely clear _exactly_ what event is causing such a high rate. (It's a separate action item on our side to categorize the rest of the events). Some random thoughts:
- Do you have any custom plugins that is generating a lot of websocket events?
- Is there any other integration that runs frequently on your instance?

But overall, it looks like after installing Elastic, overall the server is in a better place?

Maybe a related question, you initially mentioned that you are using Team edition. How were you able to use Elastic then? Did you recently purchase an enterprise license? If so, you could directly reach out to support.

**Comment by scriptdealer** [comment]
I asked guys to press Trial button to get the enterprise metrics. But instead of keeping it simple, they seem to enjoy it's features. Anyhow.. yes, we have a bunch of custom plugins. But I think we tried to disable them one by one to see if anyone affects memory usage. Alright then, should we wait for a more detailed metrics then ? Closing issue for now ?

**Comment by agnivade** [comment]
If a plugin is not responsible for this, then I guess without a code improvement to categorize the "other" events, we don't have much to go forward. But now that you have metrics and Bleve is removed, it should be easy to validate whether disabling a plugin makes a change or not. Just keep an eye on the broadcasts graph and see if there's any change. If that doesn't help, then we'll need to wait until the improvement is available.

**Comment by scriptdealer** [comment]
Thanks Agniva!
