### ISSUE TITLE
Team names not shown properly in team portion of URLs

### ISSUE THREAD

**Issue by satcomjimmy** [mattermost/mattermost#24285]
#### Summary
In a browser, the team names in the URL do not match the team names in the team settings. 

#### Steps to reproduce
We are working on a migration/consolidation project for our organization's chat apps. We stood up a new mattermost, started building teams and channels and then restored one team from a backup, so we have 3 teams. We recently upgraded, so we are now on 8.0.1. 
In a browser, the teams part of the URL is wrong on 2 of our 3 teams. The main team we want everyone to join is not the one showing "main" in the teams place in the URL, but it IS showing the team name we gave it. I would prefer the team showing "main" to show the team name we gave it as well, and the third team seems to have latched onto a team name we probably used at first before settling on the final structure of the teams. 

#### Expected behavior
I expect the URL for any particular team or channel to use the team name we assigned in settings in the team portion of the URL. Further, I expected the URL to change if we renamed the team.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54162.

**Comment by hmhealey** [comment]
> It seems that it is not possible to change team url at all.

Yeah, that's right. You're only able to change the display name of the team (the one shown in the UI) and not the URL name.

I can't remember the exact reason why we never added that ability to begin with, but this is likely a very big task to support officially since we'd need to ensure that the apps could handle redirecting users to the correct team in various places and we'd also need to ensure that anything which is keyed off the team name internally is updated accordingly. We occasionally run into similar issues with being able to rename channels, and channel names are referenced less often than team names. 

As such, this isn't something we currently plan to support. You're welcome to file a feature request for it on https://mattermost.uservoice.com/forums/306457-general though
