### ISSUE TITLE
Migrations to 8.0 on PostgreSQL take very long (MM-52615)

### ISSUE THREAD

**Issue by moschlar** [mattermost/mattermost#24338]
_Following up on
https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/MM-52615_

Updated GitLab Omnibus from 16.2 to 16.3 which updates Mattermost to 8.0.

The migration step `UPDATE fileinfo SET channelid = posts.channelid FROM posts WHERE fileinfo.channelid IS NULL AND fileinfo.postid = posts.id;` takes longer than 10 minutes (already increased `statement_timout`) and throws many of the  `word is too long to be indexed` notices.

I am aware that those are just notices, but I have a hunch that the reason for those notices is also the reason why that update query takes so long in the first place.

**Comment by moschlar** [comment]
Update: Using a `statement_timeout` of 20 minutes made it work.

**Comment by agnivade** [comment]
Thanks @moschlar. The total runtime heavily depends on the number of rows in your table. Could you let us know how many rows you currently have in your `fileinfo` table? From our testing [here](https://github.com/mattermost/mattermost/pull/22603), it took 0.27 secs for a table with 1731 rows. Granted that it's no way close to a large table.

Re: the notices, as I mentioned in https://mattermost.atlassian.net/browse/MM-52615, it's to do with the length of a word.  

Going forward, we have made changes to our schema migration policy not to make blocking queries like the above, so that irrespective of however long the query takes, your MM installation will be unaffected.

**Comment by moschlar** [comment]
@agnivade Right, we seem to be quite a little above that value :rofl: 
```
mattermost_production=# select count(*) from fileinfo;
 count  
--------
 163161
(1 row)
```

**Comment by agnivade** [comment]
Ok, so around 100x of that. So it seems the increase is not linear. Otherwise, it should have taken 27s instead of 20 minutes. Anyways, I will close this as there is no bug. Hopefully going forward, due to our schema migration policy, the time taken for migrations won't be a problem.
