### ISSUE TITLE
Option to disable cross-team invites for non-admins

### ISSUE THREAD

**Issue by JeroenAdam** [mattermost/mattermost#24393]
A bug reported on [uservoice](https://mattermost.uservoice.com/forums/306457-general/suggestions/12447363-team-setting-restrict-inviting-of-new-members), still relevant for Mattermost v8.1 Enterprise Edition Free.

The invite form is currently also the only point (tell me otherwise) where a Team member can peek and see all the other members from all the server teams.
This looks more of a bug than a feature, as the direct messages can be limited via configurable option, but any member could initiate a talk with other member (independently of the team). To do this first search for members in the team invite form, get the team name in the Join Team options, and later use the direct message url to open a direct communication: https:/server_url/team_name/messages/@user_found

Please enable to block messages between member of different teams, and more important remove the invite of members or restrict at least the invitation to use only email (not lookup for users)
Thanks!

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-54268.

**Comment by abhinav700** [comment]
@amyblais Hey, I would like to work on this issue. What are the files that I should begin  looking into?

**Comment by amyblais** [comment]
@abhinav700 I don't know if the team has triaged this ticket yet, but I've added comments/labels to the Jira ticket to indicate that you are interested in working on this.

**Comment by abhinav700** [comment]
@abhinav700 This issue has not been triaged yet. 
I will pick up on some other issue while this gets triaged.

**Comment by hmhealey** [comment]
Hi @JeroenAdam. By design, Mattermost doesn't isolate team members from each other in most cases, so we wouldn't consider this a bug. While this would be nice to add, it likely requires much more work to properly prevent users from seeing non-team-members, so this setting wouldn't be enough on its own to achieve that.

Feel free to file this as a new suggestion on Uservoice though. I imagine that'll get more visibility than a comment on a completed feature request would.
