### ISSUE TITLE
Missing non-custom emoji in the emoji picker

### ISSUE THREAD

**Issue by olivierlambert** [mattermost/mattermost#25015]
#### Summary
Missing emoji preview in the emoji picker (only for non-custom emojis)

#### Steps to reproduce
1. Updated from 9 to 9.1
2. Open the emoji picker
3. Only see the custom emojis, the default ones are here (you can hover) but they are not displayed. They work when added (so the issue is contained in the emoji picker)

#### Expected behavior
1. Open the emoji picker
2. See all the emojis

#### Observed behavior (that appears unintentional) 
Visible behavior here:

![mmemojibroken](https://github.com/mattermost/mattermost/assets/1241401/35f8edb4-c5ac-4e1b-a291-389ee08e6bca)

#### Possible fixes
I already had this issue few months (years?) ago, and it was fixed by a patch release of Mattermost. I don't remember which release it was, but it was the exact same issue.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55044.

**Comment by hmhealey** [comment]
Hi @olivierlambert. I don't think we've made any changes to that code recently, but since the emoji picker uses one big image for all built-in emojis, it's possible that you're running into a network issue loading that.

If you could:
1. Refresh the app
2. Open the dev tools (F12 in the web app or View > Developer Tools For Current Server in the desktop app)
3. Go to the Network tab and select the "Image" or "Img" filter at the top
4. Open the emoji picker
5. Find the entry for the emoji picker spritesheet. It'll be a large PNG file that's around 4.7MB.

**If you post a screenshot of that, make sure to erase the Cookie header because that contains sensitive information.**

You should see something like this, although the URL for the file will probably be different:
![Screenshot 2023-10-23 at 10 22 52 AM](https://github.com/mattermost/mattermost/assets/3277310/fa721d80-c8dc-4885-885e-7dfd7f19fd59)

That should show us if there are any errors or anything when loading that file. It might take a moment based on your connection

**Comment by olivierlambert** [comment]
Yes, I have a 404 on loading https://myhost/static/files/9ea8998d9c0389f02c43.png

What would be next?

**Comment by hmhealey** [comment]
Do you happen to know how your MM server is installed? Unless something is blocking access to that file, it sounds like the web app resources may be missing.

Alternatively, it could be caching the wrong version of the HTML that's loaded due to caching somewhere. If that's the case, opening MM in another browser or in a private tab should let the emoji picker load correctly

**Comment by olivierlambert** [comment]
Yes, I installed it myself. MM is running locally with Nginx as a reverse SSL proxy to expose it publicly. It's not a cache issue (test in no cache mode in FF with dev tools, also Nginx isn't doing caching), it's happening for all the users (so not just Firefox). Thing is: the configuration did not change since years. So I'm leaning about a missing resource (or something going wrong) during 9.1 upgrade?

**Comment by hmhealey** [comment]
That seems like what's happening. In the `mattermost` folder on your server, can you find the image on the disk? It should be at `mattermost/client/files/9ea8998d9c0389f02c43.png`. It's there in the 9.1.0 tarball at https://releases.mattermost.com/9.1.0/mattermost-9.1.0-linux-amd64.tar.gz at least

**Comment by olivierlambert** [comment]
The file was indeed missing in the folder. I manually added it from the 9.1 tarball and now it works. I don't understand why it wasn't extracted in the first place, since it is present in the tarball I initially used to update Mattermost :thinking: 

Anyway, problem solved, thanks a lot for your assistance!
