### ISSUE TITLE
Mobile: The urgent feature is not working in DMs

### ISSUE THREAD

**Issue by bitdessert** [mattermost/mattermost#25116]
### Environment Information
  - Device Name:
  - OS Version: iOS 16
  - Mattermost App Version: 2.8.0
  - Mattermost Server Version:    8.1

#### Steps to reproduce
in DM channel
Select the Urgent feature and enable send persistent notifications
Send message
A dialog pops up saying @mentioned is required

#### Expected behavior
message should be sent. 

#### Observed behavior 
A dialog pops up saying @mentioned is required

![Screenshot_20231015_185139_Mattermost (1)](https://github.com/mattermost/mattermost-mobile/assets/936315/cb900d5b-d88d-4e77-876c-d49cc707bcc7)

#### Possible fixes
When sending a urgent message in a DM, there would be no need to check for @mentions since it's already targeting a specific user.

**Comment by escofresco** [comment]
Can I take? (I'm getting some redux help for my other assigned issue and would like to fix something else in the meantime).

**Comment by escofresco** [comment]
Also wondering, under **Environment information** the "OS Version" is iOS but the subsequent screenshot is for android. Should "OS Version" also include Android?

**Comment by amyblais** [comment]
I believe this applies for both iOS and Android.

**Comment by escofresco** [comment]
@marianunez Wondering should this go back to mattermost-mobile? [I made a PR](https://github.com/mattermost/mattermost-mobile/pull/7648) that I haven't tested but I think will fix this issue because it makes a change where originally "Recipients must be @mentioned" happened regardless of channel type. Could definitely be wrong, I just couldn't find anything in mattermost repo that would lead to this error. Was there a particular reason this was transferred? I want to make sure I'm not missing something.

**Comment by marianunez** [comment]
> Was there a particular reason this was transferred? I want to make sure I'm not missing something

I moved the ticket to Mattermost main repo because we handle most open issues there and wanted to promote it for Hacktoberfest . 

The fix for this is indeed in the mobile repo like you've done with your PR. 👍

**Comment by escofresco** [comment]
We should close this because the [pr for it has been merged](https://github.com/mattermost/mattermost-mobile/pull/7648)

**Comment by marianunez** [comment]
Thanks for the contribution @escofresco!
