### ISSUE TITLE
Syntax highlight works only in mobile application

### ISSUE THREAD

**Issue by dkuzmenko-dsr** [mattermost/mattermost#25231]
#### Summary
Code block syntax highlight works only in mobile client. Does not highlight syntax in the desktop and browser versions.

Mobile exaple:
<img src="https://github.com/mattermost/mattermost/assets/144024170/1c925412-e9cf-4d37-ac17-b1e4137ca188" width="30%">

Desktop example:
![Screenshot_20231031_102325](https://github.com/mattermost/mattermost/assets/144024170/2e02bced-d81a-4c5c-addf-efed571ebb1d)

#### Steps to reproduce
Mattermost 9.1.1
Mattermost Desktop 5.5.1
Matttermost Mobile 2.9.0
Browsers: Firefox, Chrome
Desktop OS: Arch Linux
Mobile OS: OxygenOS 13.1 (Android 13)

Send a message with formatting like this:
~~~md
```html
<html>
<head>Hello</head>
<body>World</body>
</html>
```
~~~

And check how does it look in different clients.

#### Expected behavior
Highlight messages with color in all clients.

#### Observed behavior (that appears unintentional) 
Message text is not colored in web UI and MM Desktop.

#### Possible fixes
`¯\_(ツ)_/¯`

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55227.

**Comment by hmhealey** [comment]
Hi @dkuzmenko-dsr. I have a couple questions about what you're seeing:

1. In the example you posted, everything is indented by 4 spaces even though the backticks usually have to be at the start of a line. Is that example correct?
2. On the web app, when you hover over the post, do you see a label that says "HTML, XML" on the right side? That'll let me know if the issue is in the Markdown code itself preventing syntax highlighting or if there's an issue with your theme that's causing syntax highlighting to look the same as plain code

    ![Screenshot 2023-10-31 at 10 31 17 AM](https://github.com/mattermost/mattermost/assets/3277310/77412440-9f68-43c1-a854-a938185e021e)

**Comment by dkuzmenko-dsr** [comment]
Hi @hmhealey!

> In the example you posted, everything is indented by 4 spaces even though the backticks usually have to be at the start of a line. Is that example correct?

I just don't know another way to format preformatted markdown inside the preformatted markdown, sorry. Surely the preceding spaces should be removed.

> On the web app, when you hover over the post, do you see a label that says "HTML, XML" on the right side? That'll let me know if the issue is in the Markdown code itself preventing syntax highlighting or if there's an issue with your theme that's causing syntax highlighting to look the same as plain code

Yes, the labels are in place when I hover it with mouse. BTW, changing the code theme changes the theme color but doesn't enable coloring. Can it be a server-side configuration issue? Please let me know if you need any diagnostic or configuration snippets.

![Screenshot_20231101_071429](https://github.com/mattermost/mattermost/assets/144024170/67c90cbd-45a3-44e1-9742-00a47873aa72)

Thank you!

**Comment by dkuzmenko-dsr** [comment]
BTW, I've just tried to switch code theme from Solarized Dark to GitHub in MM Desktop. The theme change was applied, so if I reopen the settings I see GitHub theme selected, also I see the change in the mobile app: the code blocks are colored with a light background there. But it's still dark not colored in MM Desktop as well as in browser.
Maybe this information will help?

**Comment by hmhealey** [comment]
Thanks, that does help since it's confirmed that the highlighting library is functioning at least. I'm not sure why it isn't applying the theme colours though.

Could you send me the custom theme you're using? I wonder if there's something about it that's causing it to not load the CSS files for the syntax highlighting properly

**Comment by dkuzmenko-dsr** [comment]
@hmhealey below is my custom theme colors json string:
```
{"awayIndicator":"#f5ab00","buttonBg":"#386fe5","buttonColor":"#ffffff","centerChannelBg":"#0a111f","centerChannelColor":"#dddfe4","codeTheme":"github","dndIndicator":"#d24b4e","errorTextColor":"#d24b4e","linkColor":"#5d89ea","mentionBg":"#1c58d9","mentionBj":"#1c58d9","mentionColor":"#ffffff","mentionHighlightBg":"#133a91","mentionHighlightLink":"#a4f4f4","newMessageSeparator":"#81a3ef","onlineIndicator":"#3db887","sidebarBg":"#0f1a2e","sidebarHeaderBg":"#152231","sidebarHeaderTextColor":"#dddfe4","sidebarTeamBarBg":"#05080f","sidebarText":"#ffffff","sidebarTextActiveBorder":"#1279ba","sidebarTextActiveColor":"#ffffff","sidebarTextHoverBg":"#222c3f","sidebarUnreadText":"#ffffff"}
```
BTW, the same appears if I use any of standard themes like Denim or Indigo.

**Comment by dkuzmenko-dsr** [comment]
@hmhealey I've just tried to look up the console log and there are a number of error messages. My one of them be the cause of the issue?
![Screenshot_20231103_095851](https://github.com/mattermost/mattermost/assets/144024170/ac5ae954-4ed5-4bb1-ac47-79d8c96264de)

**Comment by hmhealey** [comment]
Oh yeah, those "Refused to apply style from..." errors are exactly the problem. Those two file names match the syntax highlighting style sheets in the MM 9.1.1 bundle I downloaded. If you visit those URLs in the browser, I expect you'll get a plain text error message of some sort which is why it's complaining about the content type.

If you have access to your server directly, you should check if those files actually exist in `mattermost/client/files`. If not, I don't know why they're missing, but if they are there, you might want to see if something is blocking you from loading those files

**Comment by dkuzmenko-dsr** [comment]
@hmhealey good suggestion. I've checked: symlinks are there but they are pointing to a not existing location. So files are not there.
Do you have any idea why it could happen? Are those files dynamically generated or static ones?

**Comment by p5n** [comment]
It is packaging issue:  https://gitlab.archlinux.org/archlinux/packaging/packages/mattermost/-/commit/25687af228c75a0cf51fe7c7d8cbc18173c14df1

**Comment by dkuzmenko-dsr** [comment]
Cool! Nice to have this resolved! It works now in both client and Chrome web for me. Thanks.

**Comment by hmhealey** [comment]
Thanks for the fix, @p5n! I had no idea why those files would be missing, but that definitely explains it
