### ISSUE TITLE
Copy Case-Number from Jira to Mattermost - Enumeration is getting active

### ISSUE THREAD

**Issue by DVTrast** [mattermost/mattermost#25334]
#### Summary
Copy Case-Number from Jira to Mattermost in any browser except Firefox - Enumeration is getting active

#### Steps to reproduce
Mark the case number from a jira case and paste it to mattermost
![grafik](https://github.com/mattermost/mattermost/assets/61227869/1b9f82da-1fa1-4977-ab81-e3e3813b5c86)

![grafik](https://github.com/mattermost/mattermost/assets/61227869/7622f534-0e0c-40bc-90e0-61f0f45107c5)

![grafik](https://github.com/mattermost/mattermost/assets/61227869/9ed292ee-7d03-4eca-aace-2bbf24a3eb9d)

This behaviour can be reproduced with all browser - except FireFox. The Jira-Plugin on mattermost is not installed.

#### Expected behavior
The link should be without enumeration:
![grafik](https://github.com/mattermost/mattermost/assets/61227869/87dcae7b-36b7-4398-9645-0226899906fb)

#### Observed behavior (that appears unintentional) 
The enumeration is present

**Comment by amyblais** [comment]
I'm able to reproduce this but I'm wondering if this is expected behaviour with markdown. @hmhealey Do you know if this is a bug or expected behaviour?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-55344 for now.

**Comment by hmhealey** [comment]
No, I don't think that's intended. For some reason, our code is detecting that this is inside a list. I'm seeing slightly different behaviour where it uses a bulleted list instead of a numbered one, but it's behaving similarly for me.

---

@DVTrast Are you using a self-hosted version of Jira? I'm wondering why it pastes as a numbered list for you and not me

**Comment by amyblais** [comment]
A note from our team: "The raw text is being copied insteads a list bullet element like: “* [Ticket](url)” so the this is working as expected to be converted to a list markdown. This is working as expected given that Jira website is adding that to the copy."

**Comment by hmhealey** [comment]
To elaborate a bit, we've talked about this as a team, and we're actually going to consider this as working-as-intended. Jira's HTML for those links includes list items (`<li>` tags), so while this is kind of a bug, it's not something we can fix on our end without adding a special case for that one link in Jira.

We appreciate the feedback since writing posts is such an important area in the app

**Comment by DVTrast** [comment]
@hmhealey sorry for my late answer - yes, we use a self-hosted version of Jira.

**Comment by DVTrast** [comment]
Thank you all for your help :-)

**Comment by hmhealey** [comment]
Thanks for that confirmation! I still don't know why Jira uses a list there, but it's kind of funny that they changed something there to make this behave diffeerently
