### ISSUE TITLE
Strong database search load (500 pq: syntax error in tsquery)

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/mattermost#25660]
#### Summary
Strong database search load

#### Steps to reproduce
When users search for channels using ctrl + k, the database becomes heavily loaded. An error appears in logs - 500 (pq: syntax error in tsquery: \"'kmdbh:*\"")

{
  "caller": "web/context.go:115",
  "err_where": "AutocompleteChannels",
  "error": "AutocompleteChannels: We encountered an error searching channels., Failed to autocomplete channels in team: could not find channel with term='kmdbh: pq: syntax error in tsquery: \"'kmdbh:*\"",
  "http_code": 500,
  "ip_addr": "10.32.65.1",
  "level": "error",
  "method": "POST",
  "msg": "We encountered an error searching channels.",
  "path": "/api/v4/channels/search",
  "request_id": "f589115c8jfitbtbepbh91njgc",
  "timestamp": "2023-12-08 10:57:54.358 +05:00",
  "user_id": "99hq4meyxtnffycnq4pkzw4ecc"
}

Mattermost v9.2.4 
postgresql 14.5

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-56099.

**Comment by agnivade** [comment]
Hey @KakEgorka - just to clarify, is the text you are entering "kmdbh:"?

**Comment by KakEgorka** [comment]
@agnivade Hi. It's a random set of characters. If you write random characters and then delete them and then write them again many times. It causes a 500 error and a load on the database.

**Comment by KakEgorka** [comment]
And users often make typos :) and when the user is such a lot, it turns out that this error is being reproduced.

**Comment by agnivade** [comment]
Thanks. So it sounds like essentially your users are load testing the database with random input. It's expected that search queries will generate some load on the DB, because a relational database isn't optimized for search. We recommend to use [elasticsearch](https://docs.mattermost.com/scale/elasticsearch.html) for customers who need a better search experience.

For the 500 error, unless I have the exact search term that's causing this, I can't repro it. Bear in mind that we try to sanitize some characters https://github.com/mattermost/mattermost/blob/88bd7b65f04060c8939d5776f96c57f3827fd853/server/channels/store/sqlstore/channel_store.go#L3580 but it's not exhaustive and sometimes it can fail. DB search is not perfect.

**Comment by KakEgorka** [comment]
@agnivade  Thanks for the answer.
But it's never happened before.
It has appeared since server version 8.0
when without the characters "<>+-()~:*\"!@&" many searches use the same load. 
I can't give you the exact text of the search. It is not in the logs. 
Is there any way to install Elasticsearch or other options to solve this problem?

**Comment by agnivade** [comment]
> It has appeared since server version 8.0

The only thing that comes to mind is: https://github.com/mattermost/mattermost/pull/20472. We removed the hardcoded english as the search language, but now take it from the postgres config. However, all the indexes still use english as their search config. So if your `default_text_search_config` is not english, there might be a performance regression.

But that change went in 7.1.0 and you mention that everything was fine till 8.0. So I am not really sure if there was anything after 8.0 that could cause this.

> I can't give you the exact text of the search. It is not in the logs.

The exact text is indeed logged after `could not find channel with term=`. Without that, it's hard to point to a root cause. 

> Is there any way to install Elasticsearch or other options to solve this problem?

You can follow the instructions here: https://docs.mattermost.com/scale/elasticsearch.html to install Elasticsearch. Note that you would need an enterprise license for that. On team edition, you could choose to use Bleve: https://docs.mattermost.com/deploy/bleve-search.html.

**Comment by agnivade** [comment]
Closing this due to lack of response. Feel free to leave a comment to reopen. Thanks.
