### ISSUE TITLE
Could not import "github.com/mattermost/platform/model" 

### ISSUE THREAD

**Issue by sulindi** [mattermost/mattermost#26353]
I am using go.  This has been working. Now I encounter problem:
Could not import "github.com/mattermost/platform/model"  Could anyone please help?

I am using 
client := model.NewAPIv4Client(serverURL)
client.AuthType = model.HEADER_BEARER
post := model.Post{}

my go version is  go1.21.5 linux/amd64

**Comment by agnivade** [comment]
`"github.com/mattermost/platform/model"` is the wrong import path. Where did you get this?

**Comment by sulindi** [comment]
Thanks, agnivade.   That was on my old code I had been using about a year ago. It was fine, but now it is a problem. I am not sure what is the problem.  I upgraded my go from v1.17.3 to 1.21.5  That seems to be the major change.

**Comment by agnivade** [comment]
Your old code must be several years old. We don't use the `platform` repo any more. The problem is that a lot of things have changed in these years. Your Go version is also a 2 year time jump, so there are a lot of things which have changed.

The new `model` path is `github.com/mattermost/mattermost/server/public/model`. But I would assume that you will need to change more than that because some functions might have been removed as well.
