### ISSUE TITLE
Bot mentions do not work

### ISSUE THREAD

**Issue by johnramsden** [mattermost/mattermost#27505]
#### Summary

When a bot user mentions another user via `@NAME`, `@here` or `@channel` they do not receive a notification.

#### Steps to reproduce

Create a bot user and mention another user. Or create a web hook and execute a mention through the hook when the user is a bot and no one will receive the notification

#### Expected behavior

Bot users should be able to mention users.

#### Observed behavior (that appears unintentional) 
We have an incoming webhook which creates a message in a channel, and when that incoming webhook posts to a channel, notifying users should receive a mention

**Comment by johnramsden** [comment]
@amyblais 

Ubuntu 20.04
Mattermost Version: 9.8.0
Database Schema Version: 120
Build Number: 8910831669
Database: postgres

**Comment by amyblais** [comment]
Thank you, is the webhook parameter set up similar to the example here https://developers.mattermost.com/integrate/webhooks/incoming/#parameters?

**Comment by johnramsden** [comment]
@amyblais In UI I did:

![Screenshot_20240703_120526](https://github.com/mattermost/mattermost/assets/8735102/3856818c-85e6-486a-9337-4b8f25131d77)

Notification is:

![Screenshot_20240703_120757-1](https://github.com/mattermost/mattermost/assets/8735102/53c0caac-d444-41bd-b667-22fe3739c4e4)

**Comment by johnramsden** [comment]
Also, I tested logging into the actual account of the BOT, and posting a message that mentions the respective users, and this **does** notify. It only does **not** notify if it's coming from the webhook

**Comment by amyblais** [comment]
@lindy65 @DHaussermann Would this be something that QA could help test if this is reproducible?

**Comment by DHaussermann** [comment]
@johnramsden I will try and reproduce this. 

Can you clarify for me a bit the distinction above between the bot posting directly Vs doing so via a webhook?

As bot users cannot log in, this is typically done via a webhook type setup. I will test by making a CURL request to mimic what a webhook might to and see of I can repro your issue.

**Comment by johnramsden** [comment]
@DHaussermann A normal user with a webhook integration is labeled as a "BOT", that is what I'm referring to as a bot user

**Comment by DHaussermann** [comment]
@johnramsden would this be a case where the post is being made on behalf of the user who owns the hook and in this case the post author shows with a `BOT` tag?
I can try something like that to see if I can repro.

For now I created a v9.8.0 server and tried the simplest case. When a bot made a post, the test user got a badge notification and a mention as expected. I just created a bot and posted with it. the payload look something like this...
```
curl -i -X POST -H 'Content-Type: application/json' -d '{"channel_id":"<my-channel>", "message":"This is a message from a bot with mention for @dkh-member01", "props":{"attachments": [{"pretext": "Look some text","text": "This is text"}]}}' -H 'Authorization: Bearer <my-bot-token>' https://<my-server-running-9.8.0>/api/v4/posts
```
I can try again and see if it works differently with a webhook. 
Do you know if you have either of these 2 options set in Integrations Management so I can create the same scenario?
![image](https://github.com/mattermost/mattermost/assets/35588783/e5adb5d7-4438-4a28-b8f8-ba993e222e23)

**Comment by johnramsden** [comment]
@DHaussermann We dont.
![Screenshot_20240705_131952](https://github.com/mattermost/mattermost/assets/8735102/53a6a666-225e-406a-8201-2d466bfc8a1d)

**Comment by DHaussermann** [comment]
Hi @johnramsden I took another look at this and I'm still unable to reproduce your issue. 

I created a webhook and sent the payload to the webhook where the post text contains and at mention for the test user. When I tried this the test user got a badge and mention as expected. 

I then noticed from your screenshot that it appears as though your hook might be putting the mention in an attachment and not simply in the post text so, I tried this as well. For both username mentions and `@here` the user or users get a mention when I try.    

![image](https://github.com/mattermost/mattermost/assets/35588783/ff17df43-ae78-42a2-aca5-264cc1e4b037)
![image](https://github.com/mattermost/mattermost/assets/35588783/936550e7-3275-4c68-b389-008155fd0d57)


Based on the 2 tests above ☝️, have I maybe misunderstood something?  


I see from your screen that the mentions are highlighted. Is it the case that you are not getting the corresponding badge notifications? Just to confirm, are you seeing this issue consistently?

**Comment by johnramsden** [comment]
@DHaussermann The user is highlighted but there is no (1), they are not auto subscribed to the thread, and no desktop notification is delivered.

We have tested with multiple users

**Comment by johnramsden** [comment]
@DHaussermann If it helps, im using https://healthchecks.io/ mattermost notification

**Comment by DHaussermann** [comment]
There are couple isolation steps that could be taken here.

For example, you could use a tool like Postman or CURL to send a test payload with a user at mention to your webhook (similar to what I did above) but that may be impractical if the issue is only on a production server as it would create test data in the channel.

Also, I'm not familiar with [healthchecks.io/](https://healthchecks.io/) but I'm curious if you have access to the payload that it's sending to your hook? If it were possible to get the payload and sanitize it removing all the sensitive and server specific data, it possible I could take a look to see if it helps reproduce the problem. 

@streamer45 if you have a moment to do so, can you look over the details here and see if you have any other suggestions?

**Comment by johnramsden** [comment]
@DHaussermann Indeed, curl works I get notified, healtheck I dont:

```
curl -i -X POST -d 'payload={"text": "Test, ignore me. @john","username": "****"}' https://********
```
![Screenshot_20240710_093700](https://github.com/mattermost/mattermost/assets/8735102/63827cea-f87e-433c-814a-0a851c06c58a)

![Screenshot_20240710_093716-1](https://github.com/mattermost/mattermost/assets/8735102/44fbb4da-dd09-4d67-8a5d-d3ce19563085)

With payload from https://healthchecks.io/ (I don't know content):

![Screenshot_20240710_093938](https://github.com/mattermost/mattermost/assets/8735102/984effc2-8fd5-453e-bc55-cbbb45e30502)


![Screenshot_20240710_093954-1](https://github.com/mattermost/mattermost/assets/8735102/c0e5faec-2aca-439f-84cd-80ac4919fc49)

**Comment by DHaussermann** [comment]
@johnramsden thanks I understand that the test payload worked as expected. 

Just 1 question here. I see the channels are different for your test Vs https://healthchecks.io . Was the webhook you used also different? I don't know of any reason it should work differently. Just curious if the same hook was used in the test.

**Comment by DHaussermann** [comment]
@johnramsden  forgot to mention, with regard to https://healthchecks.io, is there any chance they offer a utility to fire a test event?
 
It's interesting because in this case I assume there is a valid response web response code coming from the https://healthchecks.io/ side as their even **is** reaching your webhook and making a post. But I wonder if there's a way to see the payload there's sending.

**Comment by johnramsden** [comment]
@DHaussermann I just happened to trigger a notification that goes to another channel. They both exhibit the same behavior.

They give you a URI, eg: https://hc-ping.com/XXXXXXXXXXXX, and you can trigger a payload they will send to simulate an error by curling https://hc-ping.com/XXXXXXXXXXXX/fail. I'm not aware of a way to check the payload. Is there a way from mattermost to log the payload?

I am able to modify the content they will send, like the following: 

![Screenshot_20240710_121540-2](https://github.com/mattermost/mattermost/assets/8735102/f43f45df-11dc-4514-840e-f350237d45df)

**Comment by DHaussermann** [comment]
Hi @johnramsden, 
Seems like you've already determined the payload is what's different then if multiple webhooks affected but only with events from  https://healthchecks.io Is that correct?

Just to confirm, did you try taking verbatim the value in your _Description_ field and putting it in your CURL request to make sure it only happens when the event comes form https://healthchecks.io?
If so, this is very strange. I wounder if it's possible there is something weird like formating characters or something being added that are affecting the Mattermost behavior.    

Form the Mattermost side, I **believe** it's possible to get the payload for webhooks in the server log but, it's not ideal to troubleshoot on a production server. If I'm not mistaken it would only appear if your log level is DEBUG which is not something you would change lightly on a prod server. 
I'm not to familiar with it but there's also an additional flag you must set in the log settings.
![image](https://github.com/mattermost/mattermost/assets/35588783/77965171-2af5-48a6-9b01-8a9d9eb89f57)
Again, it would be easier if you had a test server with a webhook in place to try and see what that payload is.     
@hanzei  might be able to provide details or an easier way to see what the payload is that's hitting your hook.

**Comment by johnramsden** [comment]
@DHaussermann @hanzei So I attempted enabling debugging using the following settings:

![image](https://github.com/user-attachments/assets/a3291dd9-00c1-4c60-81d0-2584c54edd96)


I do not get payloads in my logs. I don't even get anything that's easily identifiable as a webhook. Just various post requests one of which I assume is the webhook.

Let me know if there's a way to obtain the webhook. 

If you're willing to experiment, you could also make a free account on healthcheck.io and verify you get the same behavior.

**Comment by johnramsden** [comment]
@DHaussermann This is also an attachment. Could that be the reason? Here are the contents from inspect element (sanitized): 

```
<div class="attachment ">
    <div class="attachment__content">
        <div class="clearfix attachment__container attachment__container--good">
            <h1 class="attachment__title"><a class="attachment__title-link" href="https://healthchecks.io/cloaked/REDACTED/" location="message_attachment" target="_blank" rel="noopener noreferrer">“Uptime Check for Production New” is UP.</a></h1>
            <div>
                <div class="attachment__body attachment__body--no_thumb">
                    <div>
                        <table class="attachment-fields">
                            <thead>
                                <tr></tr>
                            </thead>
                            <tbody>
                                <tr></tr>
                            </tbody>
                        </table>
                        <table class="attachment-fields">
                            <thead>
                                <tr>
                                    <th class="attachment-field__caption">Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="attachment-field">
                                        <p><span class="mention--highlight"><span data-mention="here">@here</span></span> <span class="mention--highlight"><span data-mention="john"><span><a class="mention-link" aria-haspopup="dialog" role="button" tabindex="0">@John Ramsden</a></span></span></span> <span data-mention="REDACTED"><span><a class="mention-link" aria-haspopup="dialog" role="button" tabindex="0">@REDACTED</a></span></span> <span data-mention="REDACTED"><span><a class="mention-link" aria-haspopup="dialog" role="button" tabindex="0">@REDACTED</a></span></span> <span data-mention="REDACTED"><span><a class="mention-link" aria-haspopup="dialog" role="button" tabindex="0">@REDACTED</a></span></span> Production uptime check failed. Sites down!</p>
                                        <p>View email for list of sites.</p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <table class="attachment-fields">
                            <thead>
                                <tr>
                                    <th class="attachment-field__caption">Project</th>
                                    <th class="attachment-field__caption">Period</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="attachment-field">
                                        <p>REDACTED.com</p>
                                    </td>
                                    <td class="attachment-field">
                                        <p>1 minute</p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <table class="attachment-fields">
                            <thead>
                                <tr>
                                    <th class="attachment-field__caption">Total Pings</th>
                                    <th class="attachment-field__caption">Last Ping</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="attachment-field">
                                        <p>116280</p>
                                    </td>
                                    <td class="attachment-field">
                                        <p>Success, now</p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div style="clear: both;"></div>
            </div>
        </div>
    </div>
</div>
```

screenshot of above:

![image](https://github.com/user-attachments/assets/9d899806-b4cf-4f33-a416-83ecc519ecc4)

**Comment by DHaussermann** [comment]
Hi @johnramsden,
I don't know of another way to try and get a payload. 
It's trivial to see the payload on a local test server with a network tunnel in front of it. This is how I do it unfortunately, you're woking on a prod server which is very different. 

That said, I can try and create an account free account a repro your issue at some point over the next couple days. 

For next steps:
1. Moving onto your results... I see  you have `@here` in a span as well as `@John Lastname` in what seems to be an `<a>` tag. I'm not sure why `@here` would be any different but for the mention of the specific user - I would try making this verbatim the user name value in Mattermost which would not contain spaces. 
If you're using the https://healthchecks.io/ user mention system try to just get some a raw data in there instead that will line up with the Matttermost username. If you're not using any at mention translation on healthchecks.io, still just try updating that unformatted text to match the username.
For ex:
Replace 
![image](https://github.com/user-attachments/assets/b69de3c9-2047-416e-896f-faa9f8a0c965)
with `@username` 
Note that Mattermost formats username based on a client setting so they can be made to look like `@Firname Lastname` but this is not a valid mention. The client is just formating it to make it more readable.
Note how is has changed after the post is made here:
![image](https://github.com/user-attachments/assets/565108c0-b7cd-402e-9192-d37d05010564)
  


Once the data with verbatim username ends up in a payload, the user should get a mention the same way they did with the curl request. 


2. Are you able to provide me a sanitized version of what's in your https://healthchecks.io _Description_ field so I can try to repro the issue with my account?

**Comment by johnramsden** [comment]
@DHaussermann Here's an example of a description field that doesn't work. The users are all verbatim. My username is `@john`

![image](https://github.com/user-attachments/assets/d76a7407-9c24-4114-b940-e790784aa3e2)


```
@here @john @REDACTED_VERBATIM @REDACTED_VERBATIM @REDACTED_VERBATIM Production uptime check failed. Sites down!

View email for list of sites.
```

**Comment by DHaussermann** [comment]
Hi @johnramsden,
Sorry for the overly obvious suggestion about the username above. Because I couldn't see the first character of the next word in your screen, I mistakenly though you had redacted your last name obviously, if your unsername is `@john` this is not the problem.   

Moving forward here...  I can make the webhook delivery work as expected in heatlthcheck.io in terms of it showing a badge when I hit a hook where the payload has an attachment which contains a mention. **But**, I'm not able to do so using the project level description. Allow me to explain:
1. In HealthCheck.io I create a webhook integration 
2. The webhook integration contains a raw request body which has the test and @ mentions within it.
![image](https://github.com/user-attachments/assets/91f984cb-bd5a-421a-92a4-d9803f427ed4)
3. I test the integration and make sure I get the badge mentions
![image](https://github.com/user-attachments/assets/dc74e964-60a7-497d-971b-29e9e1ad4e29)
4. I use the integration with a project and ensure I get the badge mentions
![image](https://github.com/user-attachments/assets/45d2d6d7-7bf1-49bf-8ea9-b944b661fb4f)


So... As you can see, the crux of the problem is what's happening with the project level description field where you're placing your data as is shown in the screens you provided above ☝️. 
The description for this field reads:
>"Additional notes for your own reference. Will appear in email alerts and Slack notifications." 

It seems you're somewhat able to make it work? I can't make this work at all. For fun I put in a distinct line of text here 
![image](https://github.com/user-attachments/assets/c21bb64d-0edf-40ca-b76c-751c462dbbaf)

Then when I used a network tunnelling tool to capture the request, this line does not appear anywhere in the payload.
![image](https://github.com/user-attachments/assets/ce7a77df-b376-4754-af5f-7f5b6d755290)

I'm confused by why the description does not get appended as it seems this is the portion of the message you are using for the at mention. 

Can you look at what is in the request body for your integration as per my step 2.?

Assuming there is nothing of interest in your  request body  - At this point I see only one obvious workaround. Rather than using a shared integration and appending project specific description, can you create a project specific integration and deliver the text in the request body of that integration? I'm curious if this would solve the issue. And if not, at least this value coming from HealthCheck.io is something I can capture with the network tunnel if it is not behaving as expected.

**Comment by johnramsden** [comment]
@DHaussermann I'm using the mattermost integration
![Screenshot_20240722_132149-1](https://github.com/user-attachments/assets/160053d7-6798-4d42-97dc-752993805001)

**Comment by DHaussermann** [comment]
@johnramsden, I suppose the work around is still valid, but thanks for pointing me in the right direction! I did not realize they had an out of the box integration for Mattermost 

The Mattermost integration **does* make use of the description field as the request body does not seem to be directly configurable. 
 Furthermore, I can finally reproduce your issue and I have captured a corresponding payload!
![image](https://github.com/user-attachments/assets/de37b2e8-780d-4e9c-b76e-2499c0d1d0cc)

Now that I have all the repro pieces give me just a bit more time to isolate. I will get back to you shortly.

**Comment by DHaussermann** [comment]
@johnramsden  
When I compare the working payload from the one produced by HealthCheck.io, the difference appears to be the type of field that the data is passed in and how the post attachment is structured. Specifically a `text` field Vs a `value` field. As well as since it's a `text` area it must be one level up at the attachment level not inside one of the fields in the field array.    

It seems like Mattermost parses the attachment contents for `text` that contain an at mention. It does not trigger a mention if a `value` filed has text that would be an at mention.

After having a quick discussion with an engineer about this, it's not yet clear if there is any known case where it is explicitly documented that the `value` inside a field of a post attachment could also trigger mentions. So, in short I cannot be sure that this is in fact a bug with Mattermost. I will open a Jira ticket later in my day to have R&D investigate this and determine if there is a bug to resolve. 

Regarding changes to the existing Mattermost integration on HealthCheck.io to make it work, it would be a bit more than simply changing `value` to `text` as fields require `value` and `text` attribute on a field does not actually render in the UI. Instead a `text` area must be at the attachment level instead of down a level in the field array. See the trucated example below.   

```
    "username": "Healthchecks.io",
    "icon_url": "https://healthchecks.io/static/img/logo-rounded-ua.svg",
    "attachments": [
        {
            "color": "danger",
            "fallback": "The check \"Ping my hook\" is DOWN.",
            "mrkdwn_in": [
                "fields"
            ],
            "title": "“Ping my hook” is DOWN.",
            "title_link": "https://healthchecks.io",
            "text": "This is the text at the attachment with ping for @dkh-sysadmin",
            "fields": [
                {
                    "title": "Description",
                    "value": "This text get's rendered with other field values but does not cause mentions"
                
                },
....
```
cc @streamer45 just FYI I'll open a ticket to confirm if the behavior on the Mattermost side is as expected. 
     
Also FYI @hanzei perhaps you've seen similar cases where an integration created by a 3rd party produced a webhook payload that did not quite work? Let me know if you have any thoughts to share.

**Comment by johnramsden** [comment]
Thanks @DHaussermann! I look forward to hearing if it's a bug or intended behavior.

**Comment by hanzei** [comment]
IIRC, mentions in the `text` field should trigger a notification. Mentions in the `fields.value` fields do not.

I'm open to debating whether or not they should. Please note that, AFAIK, it has been this way forever :tm:.

**Comment by DHaussermann** [comment]
Thanks @hanzei, I've created an investigation task here MM-59854 

I'm also curious if you've seen a case of a Mattermost integration being provided that is not working right. Perhaps we could reach out to Heath Check and let them now the user provided data should go in a `text` filed?
