### ISSUE TITLE
Doesn't work image preview for several channels

### ISSUE THREAD

**Issue by khmelevskiy** [mattermost/mattermost#27526]
Hello! I've already created an issue with Mattermost-Driver: Vaelor/python-mattermost-driver#135, but I'm not sure what the driver issue is, so I've duplicated it here.
It seems to me that the problem appeared after one of the last updates.

#### Summary
When I post the same image to different channels or try to post it multiple times on the same channel, the img preview doesn't load correctly.

#### Steps to reproduce
```
Mattermost Version: 9.9.0
Database Schema Version: 121
Build Number: 9307585135
Database: postgres

mattermostdriver==7.3.2
python version: 3.12.3
```

setup env, download any img(and name it cat.png) and run script.

``` python
import mattermostdriver


if __name__ == "__main__":
    channel_id = "<channel_id>"
    file = "cat.png"
    config = {
        "url": "<url>",
        "port": 443,
        "token": "<bot_token>",
        "scheme": "https",
        "verify": True,
    }
    driver = mattermostdriver.Driver(options=config)
    driver.login()

    file_id = driver.files.upload_file(channel_id=channel_id, files={"files": (file, open(file, "rb"))})["file_infos"][
        0
    ]["id"]

    for i in range(3):
        driver.posts.create_post(options={"channel_id": channel_id, "message": f"test{i}", "file_ids": [file_id]})
```

#### Expected behavior
-

#### Observed behavior (that appears unintentional) 
<img width="402" alt="image" src="https://github.com/mattermost/mattermost/assets/7830755/b5ce386d-1388-4f78-872c-b497bbdefeab">
<img width="492" alt="image" src="https://github.com/mattermost/mattermost/assets/7830755/9e81cd89-96df-4a81-a070-b097ef2f64f7">

#### Possible fixes
-

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59353.

**Comment by hmhealey** [comment]
Thanks for the report, @khmelevskiy!

You're not supposed to be able to make multiple posts with the same file attachment, so that part is working as intended. Do you remember which version you were on before where this might've been possible? It's possible that this worked accidentally at some point and got fixed later, but this has been the current behaviour for at least a couple years.

The closest you'll be able to get to the behaviour that you want is to upload the file multiple times for each post you make with it

**Comment by khmelevskiy** [comment]
@hmhealey 
Hello,
The thing is that I can't upload a file multiple times, this is how I'm trying to do it, see the example.
Moreover, if the same script is rerun, it will also send the image only once.
This process worked for us for more than a year, it broke about a few months ago

**Comment by hmhealey** [comment]
While that might've worked for a while, it wasn't intended to work that way. There's a number of places in MM where it assumes that a file will only be attached to a single post, and those won't work correctly if a file is attached to multiple posts.

If you can't upload the file multiple times, perhaps you could post the file once in a channel which everyone can access and then post a permalink to that post in the other channels so that users can click through to the original post. Alternatively, you could consider doing something similar, but instead of a permalink to a post, you could enable [public file links](https://docs.mattermost.com/configure/site-configuration-settings.html#public-links) and post a public link to that file in the other channels

**Comment by khmelevskiy** [comment]
Thanks for your answers, I actually figured it out and it's my stupid mistake.
I send data like this and after each sending I need to do `file_data.seek(0)` again.

```
file_data = BytesIO()
file_data.write(open(file, "rb").read())
file_data.seek(0)
```

Thank you for your time!
