### ISSUE TITLE
Constant log spam "Plugins have been disabled. Please check your logs for details"

### ISSUE THREAD

**Issue by seanm** [mattermost/mattermost#27580]
#### Summary
Every few seconds "Plugins have been disabled. Please check your logs for details" is logged. We have plugins disabled deliberately, so not sure the point of such a log.  It makes seeing other useful log messages harder.

#### Steps to reproduce
It just happens constantly on our setup, not sure if its something to do with our config or not.

#### Operating System
Ubuntu 22.04.4

#### Mattermost Server Version
Mattermost Version: 9.5.6
Database Schema Version: 119
MySQL: 8.0.37

#### Expected behavior
Not to have this log spam.

#### Observed behavior
Every few seconds "Plugins have been disabled. Please check your logs for details" is logged.

#### Log Output
Syslog messages (The same on journal for user mattermost):

```
...
Jul  4 14:32:51 servername mattermost[3713]: {"timestamp":"2024-07-04 14:32:51.658 -04:00","level":"error","msg":"ServePluginRequest: Plugins have been disabled. Please check your logs for details., Enable plugins to serve plugin requests","caller":"app/plugin_requests.go:34"}
Jul  4 14:32:54 servername mattermost[3713]: {"timestamp":"2024-07-04 14:32:54.594 -04:00","level":"error","msg":"ServePluginRequest: Plugins have been disabled. Please check your logs for details., Enable plugins to serve plugin requests","caller":"app/plugin_requests.go:34"}
```

#### Additional Information
Our plugin configuration at `/opt/mattermost/config/config.json`:

```
"PluginSettings": {
        "Enable": false,
        "EnableUploads": false,
        "AllowInsecureDownloadURL": false,
        "EnableHealthCheck": false,
        "Directory": "./plugins",
        "ClientDirectory": "./client/plugins",
        "Plugins": {},
        "PluginStates": {
            "com.mattermost.apps": {
                "Enable": true
            },
            "com.mattermost.calls": {
                "Enable": true
            },
            "com.mattermost.nps": {
                "Enable": true
            },
            "com.mattermost.plugin-channel-export": {
                "Enable": true
            },
            "com.mattermost.plugin-incident-management": {
                "Enable": true
            },
            "focalboard": {
                "Enable": true
            },
            "jira": {
                "Enable": true
            },
            "playbooks": {

                "Enable": true
            }
        },
        "EnableMarketplace": false,
        "EnableRemoteMarketplace": false,
        "AutomaticPrepackagedPlugins": false,
        "RequirePluginSignature": false,
        "MarketplaceURL": "https://api.integrations.mattermost.com",
        "SignaturePublicKeyFiles": [],
        "ChimeraOAuthProxyURL": ""
    },
```

**Comment by amyblais** [comment]
Does one of these earlier threads help with troubleshooting the issue?
 - https://forum.mattermost.com/t/mattermost-default-plugins-not-visible-after-upgrade/8484
 - https://github.com/mattermost/mattermost/issues/14412
 - https://forum.mattermost.com/t/plugins-disabled-caused-by-selinux/18528

**Comment by cjf-atlantic** [comment]
The links are not too helpful in this case because the ideia is to have the plugins disabled and have clean logs. So the question is why the logs have being populated with plugin error messages when plugins are disabled? Do we have a way to avoid these messages, is our setup wrong or is it a possible bug?

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59471.

**Comment by cjf-atlantic** [comment]
> Opened https://mattermost.atlassian.net/browse/MM-59471.

Thank you :-)

**Comment by sbishel** [comment]
Essentially there is a client out there calling the "/api/v4/plugins/{pluginName}/..." endpoint.
This is the base endpoint for a plugin API call. When the server receives a call to `api/v4/plugin` it passes that call along to the plugin. However, it checks the `PluginSettings.Enable` first, throws and logs the error. 

I can duplicate using curl after turning off plugins. But only get a single log message. I also tested that clients lose the plugin after disabling plugins. So it must be some old client or other client that keeps retrying a plugin API. 

Did this just start happening or do you know when it started? Did you ever allow plugins?

From a code perspective, we should probably check the config setting before creating the `/plugins` route, but really the problem is that rogue client.

**Comment by cjf-atlantic** [comment]
Thank you for your answer.
As far as our syslog goes (September 2023) that similar events are present in the syslog.
Since December 2022 that we have plugins disabled.
