### ISSUE TITLE
 Product menu > Integrations > OAuth 2.0 Applications missing from console

### ISSUE THREAD

**Issue by alternativesurfer** [mattermost/mattermost#27693]
Service Provider is enabled
![image](https://github.com/user-attachments/assets/ba61ae03-3c36-4730-9393-f22865ae654f)

but OAuth options are not present
![image](https://github.com/user-attachments/assets/a1ef6440-dd7b-451d-b4a2-8122989dbbc3)

**Comment by amyblais** [comment]
@alternativesurfer Can you help fill in the following details for this issue?

#### Summary
Bug report in one concise sentence.

#### Steps to reproduce
What are the steps to reproduce the issue?

#### Operating System
What Operating System do you use? (examples: Windows 10 x64, macOS Ventura 13.2 Apple Silicon, Ubuntu Linux 22.04 LTS x64)

#### Mattermost Server Version
Which version of the Mattermost Server did this occur on? (You can find your Mattermost Server version via **Mattermost Menu** > **About Mattermost**)

#### Expected behavior
What is the expected behaviour?

#### Observed behavior
What issue did you see happen?

#### Log Output
Output from the log files if applicable.

#### Additional Information
Additional helpful information, such as error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem.

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-59820.

**Comment by amyblais** [comment]
Closing as this bug is invalid.
