### ISSUE TITLE
[Help Wanted] [MM-10448] Allow emojis to trigger mentions based on keywords

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost#9233]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10448)

Currently emojis do not trigger mentions (even if they match a custom word that triggers mentions) due to: https://mattermost.atlassian.net/browse/MM-7197. The case was overlooked where certain emojis may actually be used to trigger notifications based on keywords that trigger mentions, as surfaced by a customer.

Expected: 
1. Emojis exactly matching any *custom* "words that triggers mentions" should fire mentions and be highlighted in the channel. 
2. Emojis exactly matching *usernames* should not trigger mentions and should not be highlighted in the channel.

**Comment by mszostok** [comment]
Hi, @esethna I would like to take care of it, but could you clarify what do you mean by saying 
>Emojis exactly matching any custom "words that triggers mentions"

?
I've checked the source code and introduced changes from **MM-7197** task. 

there is a `GetExplicitMentions` method where we can pass the `keywords`which are gathered from `GetMentionKeywordsInChannel` func.

By saying *custom* you mean the values from the keywords arg? Because there is a functionality for returning **"mention_keys"** set for given profile:
https://github.com/saturninoabril/mattermost-server/blob/38bab40b3238fa06c8132be41a8e860fda18b9dc/app/notification.go#L918-L926

If yes then it looks pretty easy but I'm not sure if my assumption is correct because of the label `Difficulty: Intermediate` :D

**Comment by jasonblais** [comment]
@mszostok Good question.

By "custom", we mean the "Other non-case sensitive words, separated by commas" in **Account Settings > Notifications > Words that trigger mentions**.

![image](https://user-images.githubusercontent.com/13119842/46592547-d8baf580-ca91-11e8-976d-53aa49b0512d.png)

So it does sound like what you're referring to above - though I'm not able to confirm as a non-developer :) 

/cc @hmhealey

**Comment by jasonblais** [comment]
Hi @mszostok,

How far have you gone in developing this improvement?

I just discussed with our engineering team and it sounds like there is some discussion on what can or can't be a custom mention.

It appears emojis are part of that discussion, so I wanted to hop in and see how far along you are.

**Comment by hanzei** [comment]
@mszostok Did @jasonblais answer helped you out? Do you have any other questions?

**Comment by hanzei** [comment]
Making this available to the public because there wasn't an update from @mszostok  for some time.

**Comment by jasonblais** [comment]
Hey @hanzei, just a heads up that it looks like the JIRA ticket was queued for some UX discussion, so I'll close this help wanted ticket for now. We can re-open it once it's passed UX
